// src/components/PlansSection/constants/planFeatures.js

export const starterPlan = {
  name: "Starter Plan",
  tagline: "Kickstart your journey",
  basePrice: 13500,
  duration: "30 Days",
  features: [
    { label: "Ad Budget – 35% of package on ads", available: true },
    { label: "Project Listing – Only 1 project can be listed", available: true },
    { label: "Leads – 50–70 location-based", available: true },
    { label: "Lead Sharing – Shared with 2–3 people", available: true },
    { label: "Featured Listing on home page", available: false },
    { label: "Manage Properties", available: false },
    { label: "Multiple Property Photos", available: false },
    { label: "Extra Visibility Boost", available: false },
    { label: "Graphics Included", available: false },
    { label: "Lead Shelf Life – 30 days", available: true },
  ],
  deliverables: [
    { label: "Dashboard access", available: true },
    { label: "Buyer inquiries", available: true },
    { label: "Monthly reports", available: true },
    { label: "Personal dashboard access (real-time leads)", available: true },
    { label: "Fresh daily buyer inquiries", available: true },
    { label: "Shared NCR + exclusive location-based leads", available: true },
    { label: "Responses directly visible in dashboard", available: true },
  ],
  limitations: [
    { label: "No featured listing", available: false },
    { label: "No option to manage properties", available: false },
    { label: "No multiple property photos", available: false },
    { label: "Leads only location-based (not project-based)", available: false },
  ],
  benefits: [
    { label: "Expand your business", available: true },
    { label: "Cost-effective", available: true },
    { label: "Attractive displays", available: true },
    { label: "Omni channel marketing", available: true },
    { label: "Relevant authentic buyers", available: true },
    { label: "Social media display of projects", available: true },
    { label: "Real-time search inquiries", available: true },
    { label: "Leads for Residential, Commercial, and Plots", available: true },
  ],
  buttonText: "Get Starter",
};

export const growthPlan = {
  name: "Growth Plan",
  tagline: "Scale your business",
  basePrice: 49999,
  duration: "60 Days",
  features: [
    { label: "Ad Budget – 45% of package on ads", available: true },
    { label: "Project Listing – Up to 3 projects", available: true },
    { label: "Leads – 100–150 location-based", available: true },
    { label: "Lead Sharing – Shared with 1–2 people", available: true },
    { label: "1 Featured Listing on home page", available: true },
    { label: "Manage Properties", available: true },
    { label: "Multiple Property Photos", available: true },
    { label: "5x More Visibility", available: true },
    { label: "3 Graphics Included", available: true },
    { label: "Google & YouTube Ads", available: true },
    { label: "Video Editing Support", available: true },
    { label: "Lead Shelf Life – 30 days", available: true },
  ],
  deliverables: [
    { label: "Dashboard access", available: true },
    { label: "Buyer inquiries", available: true },
    { label: "Monthly reports", available: true },
    { label: "Personal dashboard access (real-time leads)", available: true },
    { label: "Fresh daily buyer inquiries", available: true },
    { label: "Shared NCR + exclusive location-based leads", available: true },
    { label: "Responses directly in your dashboard", available: true },
  ],
  benefits: [
    { label: "Expand your business", available: true },
    { label: "Cost-effective", available: true },
    { label: "Attractive displays", available: true },
    { label: "Omni channel marketing", available: true },
    { label: "Authentic buyers", available: true },
    { label: "Social media display of projects", available: true },
    { label: "Google & YouTube ads included", available: true },
    { label: "Detailed audience creation", available: true },
    { label: "Video editing support", available: true },
    { label: "Leads for Residential, Commercial, and Plots", available: true },
  ],
  buttonText: "Upgrade to Growth",
  highlight: true, 
};

export const customPlan = {
  name: "Custom Plan",
  tagline: "Tailored for your needs",
  basePrice: null, 
  duration: null,  
  features: [
    { label: "Real-time delivery", available: true },
    { label: "Multi-city targeting", available: true },
    { label: "Shared / Exclusive routing options", available: true },
    { label: "Daily caps & flexible campaign duration", available: true },
    { label: "Bundle WhatsApp chatbot, creatives, ad ops", available: true },
    { label: "Lead nurturing add-ons available", available: true },
  ],
  deliverables: [
    { label: "Transparent monthly reports", available: true },
    { label: "GST invoice provided", available: true },
  ],
  limitations: [
    { label: "No fixed price — tailored as per requirements", available: false },
    { label: "Final scope depends on selected cities & add-ons", available: false },
  ],
  benefits: [
    { label: "Fully customizable campaign", available: true },
    { label: "Scale as per budget & needs", available: true },
    { label: "Mix & match add-ons", available: true },
    { label: "Direct support from campaign managers", available: true },
  ],
  buttonText: "Request Quote",
};

