
// ImgByID: 1
import imgID_1_01 from "../../assets/PropertiesImgAllCity/Noida01/img_01.png"
import imgID_1_02 from "../../assets/PropertiesImgAllCity/Noida01/img_02.png"
import imgID_1_03 from "../../assets/PropertiesImgAllCity/Noida01/img_03.jpeg"
import imgID_1_04 from "../../assets/PropertiesImgAllCity/Noida01/img_04.png"
import imgID_1_05 from "../../assets/PropertiesImgAllCity/Noida01/img_05.jpeg"
import imgID_1_06 from "../../assets/PropertiesImgAllCity/Noida01/img_06.png"
import imgID_1_07 from "../../assets/PropertiesImgAllCity/Noida01/img_07.jpeg"
import imgID_1_08 from "../../assets/PropertiesImgAllCity/Noida01/img_08.png"
import imgID_1_09 from "../../assets/PropertiesImgAllCity/Noida01/img_09.png"
// import imgID_1_10 from "../../assets/PropertiesImgAllCity/Noida01/img_10.png"

const imagesSet01 = [
  imgID_1_01,
  imgID_1_02,
  imgID_1_03,
  imgID_1_04,
  imgID_1_05,
  imgID_1_06,
  imgID_1_07,
  imgID_1_08,
  imgID_1_09,
  // imgID_1_10,
];


// ImgByID: 2
import imgID_2_01 from "../../assets/phome_Image/ExclusivePropertiesImg/photo_01.avif";
import imgID_2_02 from "../../assets/phome_Image/ExclusivePropertiesImg/photo_02.avif";
import imgID_2_03 from "../../assets/phome_Image/ExclusivePropertiesImg/photo_03.avif";
import imgID_2_04 from "../../assets/phome_Image/ExclusivePropertiesImg/photo_04.avif";
import imgID_2_05 from "../../assets/phome_Image/ExclusivePropertiesImg/photo_05.avif";
import imgID_2_06 from "../../assets/phome_Image/ExclusivePropertiesImg/photo_06.avif";
import imgID_2_07 from "../../assets/phome_Image/ExclusivePropertiesImg/photo_07.avif";
import imgID_2_08 from "../../assets/phome_Image/ExclusivePropertiesImg/photo_08.avif";
import imgID_2_09 from "../../assets/phome_Image/ExclusivePropertiesImg/photo_09.avif";
import imgID_2_10 from "../../assets/phome_Image/ExclusivePropertiesImg/photo_10.avif";

// ImgByID: 3


const imagesSet = [
  imgID_2_01,
  imgID_2_02,
  imgID_2_03,
  imgID_2_04,
  imgID_2_05,
  imgID_2_06,
  imgID_2_07,
  imgID_2_08,
  imgID_2_09,
  imgID_2_10,
];


// ImgByID: 3
import imgID_3_01 from "../../assets/PropertiesImgAllCity/Noida03/img_01.jpeg";
import imgID_3_02 from "../../assets/PropertiesImgAllCity/Noida03/img_02.jpeg";
import imgID_3_03 from "../../assets/PropertiesImgAllCity/Noida03/img_03.jpeg";
import imgID_3_04 from "../../assets/PropertiesImgAllCity/Noida03/img_04.jpeg";
import imgID_3_05 from "../../assets/PropertiesImgAllCity/Noida03/img_05.jpg";
// import imgID_3_06 from "../../assets/PropertiesImgAllCity/Noida02/img_06.png";
// import imgID_3_07 from "../../assets/PropertiesImgAllCity/Noida02/img_07.png";
// import imgID_3_08 from "../../assets/PropertiesImgAllCity/Noida02/img_08.png";
// import imgID_3_09 from "../../assets/PropertiesImgAllCity/Noida02/img_09.png";
// import imgID_3_10 from "../../assets/PropertiesImgAllCity/Noida02/img_10.png";

const imagesSet03 = [
  imgID_3_01,
  imgID_3_02,
  imgID_3_03,
  imgID_3_04,
  imgID_3_05,
  // imgID_3_06,
  // imgID_3_07,
  // imgID_3_08,
  // imgID_3_09,
  // imgID_3_10,
];

// ImgByID: 4
import imgID_4_01 from "../../assets/PropertiesImgAllCity/Noida04/img_01.jpeg";
import imgID_4_02 from "../../assets/PropertiesImgAllCity/Noida04/img_02.jpeg";
import imgID_4_03 from "../../assets/PropertiesImgAllCity/Noida04/img_03.jpeg";
import imgID_4_04 from "../../assets/PropertiesImgAllCity/Noida04/img_04.jpeg";
import imgID_4_05 from "../../assets/PropertiesImgAllCity/Noida04/img_05.jpeg";
import imgID_4_06 from "../../assets/PropertiesImgAllCity/Noida04/img_06.jpeg";
import imgID_4_07 from "../../assets/PropertiesImgAllCity/Noida04/img_07.jpeg";
import imgID_4_08 from "../../assets/PropertiesImgAllCity/Noida04/img_08.jpeg";
// import imgID_4_09 from "../../assets/PropertiesImgAllCity/Noida04/img_09.jpeg";
import imgID_4_10 from "../../assets/PropertiesImgAllCity/Noida04/img_10.jpeg";

const imagesSet04 = [
  imgID_4_01,
  imgID_4_02,
  imgID_4_03,
  imgID_4_04,
  imgID_4_05,
  imgID_4_06,
  imgID_4_07,
  imgID_4_08,
  // imgID_4_09,
  imgID_4_10,
];

//  Generate 70 properties (10 for each location)
const dummyProperties = [


  // ---------- Delhi NCR (1–10) ----------

  //
  {
    id: 1,
    title: "Modern 2 BHK in Noida Sector 62",
    status: "Ready to Move",
    transaction: "New Property",
    furnishing: "Semi-Furnished",
    society: "Sunshine Residency",
    propertyType: "Apartment",
    bhk: "2 BHK",
    area: { builtUp: "1200 sq.ft" },
    price: "₹80 Lac",
    carpetArea: "950 sq.ft",
    pricePerSqft: "₹6667 / sq.ft",
    maintenance: "₹2,000 per month",
    location: { city: "Delhi NCR", locality: "Sector 62", landmark: "Near City Centre Metro Station" },
    carParking: "Covered",
    description: "Spacious 2 BHK with modern amenities in the heart of Noida.",
    images: imagesSet04,
    amenities: ["Lift", "24x7 Security", "Gym", "Power Backup", "Community Hall", "Swimming Pool"],
    floorPlan: "https://example.com/floorplan/2bhk-noida.jpg",
    mapLocation: { lat: 28.628, lng: 77.365 },
    intent: "high",
    postedOn: "today",
    postedAt: "2025-09-19T10:30:00Z",
    contact: {
      name: "Amit Sharma",
      phone: "+91 9876543210",
      email: "amit.sharma@propertybrokers.com",
      whatsapp: "https://wa.me/919876543210",
      scheduleVisitLink: "https://calendly.com/amit-property/visit",
    },
    highlights: ["Corner property with extra sunlight", "Near IT Hub & Metro", "High rental demand area"],
    legalClearance: ["RERA Approved", "Bank Loan Available", "Clear Title"],
  },
  {
    id: 2,
    title: "Luxury Villa in Delhi NCR DLF Phase 2",
    status: "Ready to Move",
    transaction: "Resale",
    furnishing: "Furnished",
    society: "DLF Villas",
    propertyType: "Villa",
    bhk: "5 BHK",
    area: { builtUp: "4500 sq.ft" },
    price: "₹6.5 Cr",
    carpetArea: "4000 sq.ft",
    pricePerSqft: "₹14,444 / sq.ft",
    maintenance: "₹10,000 per month",
    location: { city: "Delhi NCR", locality: "DLF Phase 2", landmark: "Near CyberHub" },
    carParking: "3 Covered",
    description: "Premium villa with landscaped garden and private pool.",
    images: imagesSet04,
    amenities: ["Private Pool", "Gym", "Servant Room", "Home Theater", "Power Backup"],
    floorPlan: "https://example.com/floorplan/villa-dlf.jpg",
    mapLocation: { lat: 28.482, lng: 77.092 },
    intent: "high",
    postedOn: "yesterday",
    postedAt: "2025-09-18T11:45:00Z",
    contact: {
      name: "Rohit Verma",
      phone: "+91 9876512345",
      email: "rohit.verma@propertygurgaon.com",
      whatsapp: "https://wa.me/919876512345",
      scheduleVisitLink: "https://calendly.com/rohit-villa/visit",
    },
    highlights: ["Close to CyberHub", "Private garden", "High resale value"],
    legalClearance: ["RERA Approved", "Loan Available", "Mutation Done"],
  },
  {
    id: 3,
    title: "Office Space in Connaught Place, Delhi NCR",
    status: "Ready to Move",
    transaction: "New Property",
    furnishing: "Unfurnished",
    society: "Statesman House",
    propertyType: "Office",
    area: { builtUp: "2500 sq.ft" },
    price: "₹5 Cr",
    carpetArea: "2100 sq.ft",
    pricePerSqft: "₹20,000 / sq.ft",
    maintenance: "₹12,000 per month",
    location: { city: "Delhi NCR", locality: "Connaught Place", landmark: "Near Rajiv Chowk Metro" },
    carParking: "2 Open",
    description: "Premium Grade-A office space in CP with 24/7 access.",
    images: imagesSet,
    amenities: ["Lift", "Power Backup", "CCTV", "Conference Room", "Fire Safety"],
    floorPlan: "https://example.com/floorplan/office-cp.jpg",
    mapLocation: { lat: 28.632, lng: 77.219 },
    intent: "medium",
    postedOn: "this week",
    postedAt: "2025-09-15T09:00:00Z",
    contact: {
      name: "Simran Khurana",
      phone: "+91 9876001234",
      email: "simran.k@delhioffice.com",
      whatsapp: "https://wa.me/919876001234",
      scheduleVisitLink: "https://calendly.com/simran-office/visit",
    },
    highlights: ["Prime location", "Metro connectivity", "High demand area"],
    legalClearance: ["RERA Approved", "Fire NOC Available"],
  },
  {
    id: 4,
    title: "Industrial Land in Faridabad",
    status: "Ready to Move",
    transaction: "Resale",
    furnishing: "Unfurnished",
    society: "Sector 58 Industrial Zone",
    propertyType: "Industrial Land",
    area: { builtUp: "1 Acre" },
    price: "₹12 Cr",
    carpetArea: "N/A",
    pricePerSqft: "₹2,754 / sq.yd",
    location: { city: "Faridabad", locality: "Sector 58", landmark: "Near NHPC Chowk" },
    carParking: "N/A",
    description: "Industrial land suitable for factories and warehouses.",
    images: imagesSet,
    amenities: ["Wide Roads", "Electricity Supply", "Water Connection"],
    mapLocation: { lat: 28.408, lng: 77.317 },
    intent: "medium",
    postedOn: "this week",
    postedAt: "2025-09-17T14:00:00Z",
    contact: {
      name: "Karan Mehta",
      phone: "+91 9876123456",
      email: "karan.mehta@landbrokers.com",
      whatsapp: "https://wa.me/919876123456",
      scheduleVisitLink: "https://calendly.com/karan-land/visit",
    },
    highlights: ["NHPC Chowk proximity", "Industrial zone approved", "Clear title"],
    legalClearance: ["RERA Approved", "Industrial License"],
  },
  {
    id: 5,
    title: "Townhouse in Greater Noida Sector Zeta",
    status: "Under Construction",
    transaction: "New Property",
    furnishing: "Semi-Furnished",
    society: "Zeta Villas",
    propertyType: "Townhouse",
    bhk: "3 BHK",
    area: { builtUp: "2200 sq.ft" },
    price: "₹1.2 Cr",
    carpetArea: "1800 sq.ft",
    pricePerSqft: "₹5454 / sq.ft",
    location: { city: "Greater Noida", locality: "Sector Zeta I", landmark: "Near Pari Chowk" },
    carParking: "2 Covered",
    description: "Modern townhouse with private terrace garden.",
    images: imagesSet,
    amenities: ["Terrace Garden", "Club House", "Swimming Pool"],
    floorPlan: "https://example.com/floorplan/townhouse-zeta.jpg",
    mapLocation: { lat: 28.472, lng: 77.503 },
    intent: "medium",
    postedOn: "today",
    postedAt: "2025-09-19T08:30:00Z",
    contact: {
      name: "Nidhi Bansal",
      phone: "+91 9876334567",
      email: "nidhi.bansal@gnproperty.com",
      whatsapp: "https://wa.me/919876334567",
      scheduleVisitLink: "https://calendly.com/nidhi-townhouse/visit",
    },
    highlights: ["Private terrace garden", "Modern design", "High appreciation potential"],
    legalClearance: ["RERA Approved", "Loan Available"],
  },
  {
    id: 6,
    title: "Premium Penthouse in Gurugram Golf Course Road",
    status: "Ready to Move",
    transaction: "New Property",
    furnishing: "Furnished",
    society: "Golf Edge Towers",
    propertyType: "Penthouse",
    bhk: "4 BHK",
    area: { builtUp: "5000 sq.ft" },
    price: "₹9 Cr",
    carpetArea: "4500 sq.ft",
    pricePerSqft: "₹18,000 / sq.ft",
    location: { city: "Gurgaon", locality: "Golf Course Road", landmark: "Near DLF Golf Club" },
    carParking: "3 Covered",
    description: "Exclusive penthouse with rooftop pool and city views.",
    images: imagesSet,
    amenities: ["Private Pool", "Jacuzzi", "Clubhouse", "Gym", "CCTV"],
    floorPlan: "https://example.com/floorplan/penthouse-gurgaon.jpg",
    mapLocation: { lat: 28.45, lng: 77.1 },
    intent: "high",
    postedOn: "yesterday",
    postedAt: "2025-09-18T15:00:00Z",
    contact: {
      name: "Ritu Kapoor",
      phone: "+91 9876991122",
      email: "ritu.kapoor@luxurygurgaon.com",
      whatsapp: "https://wa.me/919876991122",
      scheduleVisitLink: "https://calendly.com/ritu-penthouse/visit",
    },
    highlights: ["Skyline views", "Luxury interior", "Exclusive community"],
    legalClearance: ["RERA Approved", "Loan Available"],
  },
  {
    id: 7,
    title: "Warehouse in Ghaziabad Industrial Area",
    status: "Ready to Move",
    transaction: "Resale",
    furnishing: "Unfurnished",
    society: "Industrial Park 2",
    propertyType: "Warehouse",
    area: { builtUp: "20,000 sq.ft" },
    price: "₹15 Cr",
    carpetArea: "N/A",
    pricePerSqft: "₹7,500 / sq.ft",
    location: { city: "Ghaziabad", locality: "Industrial Area", landmark: "Near NH24" },
    carParking: "Truck Parking",
    description: "Large warehouse suitable for logistics and storage.",
    images: imagesSet,
    amenities: ["Wide Road Access", "Power Backup", "Security"],
    mapLocation: { lat: 28.67, lng: 77.45 },
    intent: "medium",
    postedOn: "this week",
    postedAt: "2025-09-16T10:00:00Z",
    contact: {
      name: "Arun Malhotra",
      phone: "+91 9876222333",
      email: "arun@warehousedeals.com",
      whatsapp: "https://wa.me/919876222333",
      scheduleVisitLink: "https://calendly.com/arun-warehouse/visit",
    },
    highlights: ["Highway access", "Industrial zone", "Large storage"],
    legalClearance: ["Factory License", "RERA Approved"],
  },
  {
    id: 8,
    title: "Commercial Shop in Karol Bagh, Delhi",
    status: "Ready to Move",
    transaction: "Resale",
    furnishing: "Semi-Furnished",
    society: "Karol Bagh Market",
    propertyType: "Shop",
    area: { builtUp: "400 sq.ft" },
    price: "₹1.8 Cr",
    carpetArea: "350 sq.ft",
    pricePerSqft: "₹45,000 / sq.ft",
    location: { city: "New Delhi", locality: "Karol Bagh", landmark: "Ajmal Khan Road" },
    carParking: "Street",
    description: "Prime retail shop in busy Karol Bagh market area.",
    images: imagesSet,
    amenities: ["Footfall Area", "Electricity", "CCTV"],
    mapLocation: { lat: 28.65, lng: 77.19 },
    intent: "high",
    postedOn: "today",
    postedAt: "2025-09-19T12:00:00Z",
    contact: {
      name: "Manoj Gupta",
      phone: "+91 9876445566",
      email: "manoj@delhishops.com",
      whatsapp: "https://wa.me/919876445566",
      scheduleVisitLink: "https://calendly.com/manoj-shop/visit",
    },
    highlights: ["High footfall", "Metro nearby", "Main road property"],
    legalClearance: ["RERA Approved", "Shop License"],
  },
  {
    id: 9,
    title: "Hotel Apartment in Aerocity, Delhi",
    status: "Under Construction",
    transaction: "New Property",
    furnishing: "Furnished",
    society: "Aerocity Suites",
    propertyType: "Hotel Apartment",
    bhk: "1 BHK",
    area: { builtUp: "750 sq.ft" },
    price: "₹1.5 Cr",
    carpetArea: "680 sq.ft",
    pricePerSqft: "₹20,000 / sq.ft",
    location: { city: "New Delhi", locality: "Aerocity", landmark: "Near IGI Airport" },
    carParking: "1 Covered",
    description: "Serviced hotel apartment ideal for investors and NRIs.",
    images: imagesSet,
    amenities: ["Concierge Service", "Spa", "Restaurant", "Swimming Pool"],
    floorPlan: "https://example.com/floorplan/hotel-apartment.jpg",
    mapLocation: { lat: 28.55, lng: 77.09 },
    intent: "high",
    postedOn: "this week",
    postedAt: "2025-09-17T11:30:00Z",
    contact: {
      name: "Priya Singh",
      phone: "+91 9876556677",
      email: "priya.singh@aerocity.com",
      whatsapp: "https://wa.me/919876556677",
      scheduleVisitLink: "https://calendly.com/priya-hotel/visit",
    },
    highlights: ["Near Airport", "Fully serviced", "Rental income potential"],
    legalClearance: ["RERA Approved", "Hotel License"],
  },
  {
    id: 10,
    title: "Mixed Use Land in Delhi NCR Expressway",
    status: "Ready to Move",
    transaction: "Resale",
    furnishing: "Unfurnished",
    society: "Expressway Commercial Belt",
    propertyType: "Mixed Use Land",
    area: { builtUp: "5 Acres" },
    price: "₹60 Cr",
    carpetArea: "N/A",
    pricePerSqft: "₹12,000 / sq.yd",
    location: { city: "Delhi NCR", locality: "Expressway", landmark: "Near Sector 142 Metro" },
    carParking: "N/A",
    description: "Prime mixed-use land for residential + commercial projects.",
    images: imagesSet,
    amenities: ["Wide Road Access", "Electricity", "Drainage"],
    mapLocation: { lat: 28.50, lng: 77.39 },
    intent: "high",
    postedOn: "yesterday",
    postedAt: "2025-09-18T09:45:00Z",
    contact: {
      name: "Vikas Anand",
      phone: "+91 9876778899",
      email: "vikas.anand@noidaproperties.com",
      whatsapp: "https://wa.me/919876778899",
      scheduleVisitLink: "https://calendly.com/vikas-land/visit",
    },
    highlights: ["Expressway location", "Suitable for IT Park", "Future metro connectivity"],
    legalClearance: ["RERA Approved", "Clear Title"],
  },

  // ---------- Mumbai (11–15) ----------
  {
    id: 11,
    title: "3 BHK Sea Facing Apartment in Worli, Mumbai",
    status: "Ready to Move",
    transaction: "Resale",
    furnishing: "Furnished",
    society: "Worli Heights",
    propertyType: "Apartment",
    bhk: "3 BHK",
    area: { builtUp: "2000 sq.ft" },
    price: "₹12 Cr",
    carpetArea: "1700 sq.ft",
    pricePerSqft: "₹60,000 / sq.ft",
    location: { city: "Mumbai", locality: "Worli", landmark: "Near Worli Sea Face" },
    carParking: "2 Covered",
    description: "Luxurious sea-facing apartment with Italian interiors.",
    images: imagesSet,
    amenities: ["Infinity Pool", "Gym", "Clubhouse"],
    mapLocation: { lat: 19.0, lng: 72.82 },
    intent: "high",
    postedOn: "today",
    postedAt: "2025-09-19T13:00:00Z",
    contact: {
      name: "Sanjay Patel",
      phone: "+91 9876999000",
      email: "sanjay.patel@mumbaiproperties.com",
      whatsapp: "https://wa.me/919876999000",
      scheduleVisitLink: "https://calendly.com/sanjay-apartment/visit",
    },
    highlights: ["Sea facing", "Luxury interiors", "Prime location"],
    legalClearance: ["RERA Approved", "OC Received"],
  },
  {
    id: 12,
    title: "Commercial Showroom in Bandra Linking Road",
    status: "Ready to Move",
    transaction: "Resale",
    furnishing: "Semi-Furnished",
    society: "Linking Road Market",
    propertyType: "Showroom",
    area: { builtUp: "1500 sq.ft" },
    price: "₹10 Cr",
    carpetArea: "1300 sq.ft",
    pricePerSqft: "₹66,667 / sq.ft",
    location: { city: "Mumbai", locality: "Bandra West", landmark: "Linking Road" },
    carParking: "Street",
    description: "Prime retail showroom with high footfall.",
    images: imagesSet04,
    amenities: ["Main Road Facing", "AC Provision", "CCTV"],
    mapLocation: { lat: 19.06, lng: 72.83 },
    intent: "high",
    postedOn: "this week",
    postedAt: "2025-09-16T15:30:00Z",
    contact: {
      name: "Neha Mehra",
      phone: "+91 9876001111",
      email: "neha.mehra@bandrashops.com",
      whatsapp: "https://wa.me/919876001111",
      scheduleVisitLink: "https://calendly.com/neha-showroom/visit",
    },
    highlights: ["High footfall", "Prime retail zone", "Metro nearby"],
    legalClearance: ["RERA Approved", "Shop License"],
  },
  {
    id: 13,
    title: "Luxury Hotel Apartment in Juhu",
    status: "Under Construction",
    transaction: "New Property",
    furnishing: "Furnished",
    society: "Juhu Bay Residences",
    propertyType: "Hotel Apartment",
    bhk: "2 BHK",
    area: { builtUp: "1400 sq.ft" },
    price: "₹5.5 Cr",
    carpetArea: "1200 sq.ft",
    pricePerSqft: "₹39,285 / sq.ft",
    location: { city: "Mumbai", locality: "Juhu", landmark: "Near Juhu Beach" },
    carParking: "1 Covered",
    description: "Luxury serviced apartments by the beach with concierge.",
    images: imagesSet,
    amenities: ["Spa", "Restaurant", "Valet Parking"],
    mapLocation: { lat: 19.1, lng: 72.82 },
    intent: "medium",
    postedOn: "yesterday",
    postedAt: "2025-09-18T12:00:00Z",
    contact: {
      name: "Anjali Nair",
      phone: "+91 9876333444",
      email: "anjali.nair@juhuresidences.com",
      whatsapp: "https://wa.me/919876333444",
      scheduleVisitLink: "https://calendly.com/anjali-hotel/visit",
    },
    highlights: ["Near Juhu Beach", "Luxury interiors", "Serviced residence"],
    legalClearance: ["RERA Approved"],
  },
  {
    id: 14,
    title: "Factory Land in Navi Mumbai MIDC",
    status: "Ready to Move",
    transaction: "Resale",
    furnishing: "Unfurnished",
    society: "MIDC Industrial Area",
    propertyType: "Factory",
    area: { builtUp: "2 Acres" },
    price: "₹25 Cr",
    carpetArea: "N/A",
    pricePerSqft: "₹11,363 / sq.yd",
    location: { city: "Navi Mumbai", locality: "MIDC", landmark: "Near Taloja" },
    carParking: "Truck Parking",
    description: "Industrial factory land in MIDC Taloja for heavy industry.",
    images: imagesSet,
    amenities: ["Wide Roads", "Power Supply", "Drainage"],
    mapLocation: { lat: 19.1, lng: 73.1 },
    intent: "medium",
    postedOn: "this week",
    postedAt: "2025-09-15T11:00:00Z",
    contact: {
      name: "Vivek Deshmukh",
      phone: "+91 9876222444",
      email: "vivek.deshmukh@midcproperty.com",
      whatsapp: "https://wa.me/919876222444",
      scheduleVisitLink: "https://calendly.com/vivek-factory/visit",
    },
    highlights: ["Industrial zone", "MIDC approved", "Heavy industry allowed"],
    legalClearance: ["Industrial License", "RERA Approved"],
  },
  {
    id: 15,
    title: "Penthouse in South Mumbai, Marine Drive",
    status: "Ready to Move",
    transaction: "Resale",
    furnishing: "Furnished",
    society: "Marine View Towers",
    propertyType: "Penthouse",
    bhk: "5 BHK",
    area: { builtUp: "6000 sq.ft" },
    price: "₹40 Cr",
    carpetArea: "5200 sq.ft",
    pricePerSqft: "₹66,667 / sq.ft",
    location: { city: "Mumbai", locality: "Marine Drive", landmark: "Near Nariman Point" },
    carParking: "4 Covered",
    description: "Ultra-luxury penthouse with Arabian Sea views.",
    images: imagesSet,
    amenities: ["Infinity Pool", "Gym", "Private Deck"],
    mapLocation: { lat: 18.94, lng: 72.82 },
    intent: "high",
    postedOn: "today",
    postedAt: "2025-09-19T09:15:00Z",
    contact: {
      name: "Rajesh Kapoor",
      phone: "+91 9876777788",
      email: "rajesh.kapoor@luxurymumbai.com",
      whatsapp: "https://wa.me/919876777788",
      scheduleVisitLink: "https://calendly.com/rajesh-penthouse/visit",
    },
    highlights: ["Arabian Sea view", "Luxury interiors", "Prime address"],
    legalClearance: ["RERA Approved", "OC Received"],
  },

  // ---------- Dubai (16–20) ----------
  {
    id: 16,
    title: "Luxury Villa Compound in Palm Jumeirah, Dubai",
    status: "Ready to Move",
    transaction: "New Property",
    furnishing: "Furnished",
    society: "Palm Villa Residences",
    propertyType: "Villa Compound",
    bhk: "6 BHK",
    area: { builtUp: "10,000 sq.ft" },
    price: "AED 25M",
    carpetArea: "9000 sq.ft",
    pricePerSqft: "AED 2,777 / sq.ft",
    location: { city: "Dubai", locality: "Palm Jumeirah", landmark: "Beachfront" },
    carParking: "5 Covered",
    description: "Exclusive beachfront villa compound with private beach.",
    images: imagesSet,
    amenities: ["Private Beach", "Infinity Pool", "Spa", "Smart Home"],
    mapLocation: { lat: 25.11, lng: 55.14 },
    intent: "high",
    postedOn: "today",
    postedAt: "2025-09-19T17:00:00Z",
    contact: {
      name: "Ali Hassan",
      phone: "+971 500112233",
      email: "ali.hassan@dubailuxury.com",
      whatsapp: "https://wa.me/971500112233",
      scheduleVisitLink: "https://calendly.com/ali-villa/visit",
    },
    highlights: ["Palm Jumeirah", "Private beach", "Luxury lifestyle"],
    legalClearance: ["Dubai Land Dept Approved"],
  },
  {
    id: 17,
    title: "Office Tower Floor in Downtown Dubai",
    status: "Ready to Move",
    transaction: "Resale",
    furnishing: "Furnished",
    society: "Burj Business Tower",
    propertyType: "Floor",
    area: { builtUp: "15,000 sq.ft" },
    price: "AED 80M",
    carpetArea: "14,000 sq.ft",
    pricePerSqft: "AED 5,333 / sq.ft",
    location: { city: "Dubai", locality: "Downtown", landmark: "Near Burj Khalifa" },
    carParking: "20 Reserved",
    description: "Entire office floor with Burj Khalifa views.",
    images: imagesSet,
    amenities: ["Concierge", "CCTV", "Conference Rooms", "Valet Parking"],
    mapLocation: { lat: 25.197, lng: 55.274 },
    intent: "high",
    postedOn: "this week",
    postedAt: "2025-09-16T10:30:00Z",
    contact: {
      name: "Fatima Noor",
      phone: "+971 522334455",
      email: "fatima.noor@dubaitowers.com",
      whatsapp: "https://wa.me/971522334455",
      scheduleVisitLink: "https://calendly.com/fatima-office/visit",
    },
    highlights: ["Downtown Dubai", "Burj Khalifa view", "Premium tower"],
    legalClearance: ["Dubai Land Dept Approved"],
  },
  {
    id: 18,
    title: "Warehouse in Jebel Ali Free Zone, Dubai",
    status: "Ready to Move",
    transaction: "New Property",
    furnishing: "Unfurnished",
    society: "JAFZA Industrial Hub",
    propertyType: "Warehouse",
    area: { builtUp: "50,000 sq.ft" },
    price: "AED 120M",
    carpetArea: "N/A",
    pricePerSqft: "AED 2,400 / sq.ft",
    location: { city: "Dubai", locality: "Jebel Ali", landmark: "Near Port" },
    carParking: "Truck Parking",
    description: "Massive warehouse in free zone with tax benefits.",
    images: imagesSet,
    amenities: ["Free Zone Benefits", "Port Access", "CCTV"],
    mapLocation: { lat: 25.02, lng: 55.06 },
    intent: "medium",
    postedOn: "yesterday",
    postedAt: "2025-09-18T14:00:00Z",
    contact: {
      name: "Mohammed Saeed",
      phone: "+971 566778899",
      email: "mohammed.saeed@dubaiwarehouse.com",
      whatsapp: "https://wa.me/971566778899",
      scheduleVisitLink: "https://calendly.com/mohammed-warehouse/visit",
    },
    highlights: ["JAFZA Free Zone", "Near Port", "Tax benefits"],
    legalClearance: ["Free Zone License Approved"],
  },
  {
    id: 19,
    title: "Hotel Apartment in Dubai Marina",
    status: "Under Construction",
    transaction: "New Property",
    furnishing: "Furnished",
    society: "Marina Suites",
    propertyType: "Hotel Apartment",
    bhk: "Studio",
    area: { builtUp: "600 sq.ft" },
    price: "AED 1.2M",
    carpetArea: "550 sq.ft",
    pricePerSqft: "AED 2000 / sq.ft",
    location: { city: "Dubai", locality: "Marina", landmark: "Near Marina Mall" },
    carParking: "1 Covered",
    description: "Serviced apartment with high rental yield in Marina.",
    images: imagesSet,
    amenities: ["Concierge", "Pool", "Gym"],
    mapLocation: { lat: 25.08, lng: 55.14 },
    intent: "high",
    postedOn: "today",
    postedAt: "2025-09-19T09:45:00Z",
    contact: {
      name: "Sara Khan",
      phone: "+971 511223344",
      email: "sara.khan@marinasuites.com",
      whatsapp: "https://wa.me/971511223344",
      scheduleVisitLink: "https://calendly.com/sara-hotel/visit",
    },
    highlights: ["Dubai Marina", "High rental yield", "Fully serviced"],
    legalClearance: ["Dubai Land Dept Approved"],
  },
  {
    id: 20,
    title: "Bulk Commercial Unit in Business Bay, Dubai",
    status: "Ready to Move",
    transaction: "Resale",
    furnishing: "Unfurnished",
    society: "Business Bay Towers",
    propertyType: "Bulk Unit",
    area: { builtUp: "1,00,000 sq.ft" },
    price: "AED 300M",
    carpetArea: "95,000 sq.ft",
    pricePerSqft: "AED 3000 / sq.ft",
    location: { city: "Dubai", locality: "Business Bay", landmark: "Near Dubai Canal" },
    carParking: "50 Reserved",
    description: "Entire bulk unit available for IT or corporate offices.",
    images: imagesSet,
    amenities: ["CCTV", "Conference Rooms", "Parking", "24x7 Security"],
    mapLocation: { lat: 25.19, lng: 55.27 },
    intent: "high",
    postedOn: "this week",
    postedAt: "2025-09-17T16:30:00Z",
    contact: {
      name: "Omar Al Farsi",
      phone: "+971 588889999",
      email: "omar.alfarsi@businessbay.com",
      whatsapp: "https://wa.me/971588889999",
      scheduleVisitLink: "https://calendly.com/omar-bulkunit/visit",
    },
    highlights: ["Business Bay", "Corporate hub", "Prime investment"],
    legalClearance: ["Dubai Land Dept Approved"],
  },

  // ---------- Noida (21–30) ----------
{
  id: 21,
  title: "Luxury 3 BHK Apartment in Noida Sector 150",
  status: "Ready to Move",
  transaction: "New Property",
  furnishing: "Furnished",
  society: "ATS Pristine",
  propertyType: "Apartment",
  bhk: "3 BHK",
  area: { builtUp: "1800 sq.ft" },
  price: "₹1.4 Cr",
  carpetArea: "1500 sq.ft",
  pricePerSqft: "₹7,778 / sq.ft",
  location: { city: "Noida", locality: "Sector 150", landmark: "Near Yamuna Expressway" },
  carParking: "2 Covered",
  description: "Spacious 3 BHK apartment in greenest sector of Noida.",
  images: imagesSet01,
  amenities: ["Swimming Pool", "Clubhouse", "Jogging Track", "24x7 Security"],
  mapLocation: { lat: 28.493, lng: 77.49 },
  intent: "high",
  postedOn: "today",
  postedAt: "2025-09-21T11:00:00Z",
  contact: {
    name: "Rohit Gupta",
    phone: "+91 9811122233",
    email: "rohit.gupta@atsnoida.com",
    whatsapp: "https://wa.me/919811122233",
    scheduleVisitLink: "https://calendly.com/rohit-ats/visit"
  },
  highlights: ["Green Sector", "Sports facilities", "Modern interiors"],
  legalClearance: ["RERA Approved", "Bank Loan Available"]
},
{
  id: 22,
  title: "Premium Villa in Noida Sector 128",
  status: "Ready to Move",
  transaction: "Resale",
  furnishing: "Semi-Furnished",
  society: "Jaypee Greens",
  propertyType: "Villa",
  bhk: "5 BHK",
  area: { builtUp: "5000 sq.ft" },
  price: "₹6.5 Cr",
  carpetArea: "4500 sq.ft",
  pricePerSqft: "₹13,000 / sq.ft",
  location: { city: "Noida", locality: "Sector 128", landmark: "Jaypee Wish Town" },
  carParking: "3 Covered",
  description: "Golf course facing luxury villa with modern architecture.",
  images: imagesSet,
  amenities: ["Golf Course", "Clubhouse", "Private Garden", "Security"],
  mapLocation: { lat: 28.55, lng: 77.38 },
  intent: "high",
  postedOn: "this week",
  postedAt: "2025-09-18T13:30:00Z",
  contact: {
    name: "Pooja Malhotra",
    phone: "+91 9899888777",
    email: "pooja.malhotra@jaypeevillas.com",
    whatsapp: "https://wa.me/919899888777",
    scheduleVisitLink: "https://calendly.com/pooja-villa/visit"
  },
  highlights: ["Golf course facing", "Luxury interiors", "Gated community"],
  legalClearance: ["Clear Title", "RERA Approved"]
},
{
  id: 23,
  title: "Office Space in Noida Sector 62",
  status: "Ready to Move",
  transaction: "Resale",
  furnishing: "Furnished",
  society: "Logix Cyber Park",
  propertyType: "Office",
  area: { builtUp: "3000 sq.ft" },
  price: "₹2.4 Cr",
  carpetArea: "2700 sq.ft",
  pricePerSqft: "₹8,000 / sq.ft",
  location: { city: "Noida", locality: "Sector 62", landmark: "Near NH-24" },
  carParking: "4 Reserved",
  description: "Furnished office space with 40 workstations, meeting rooms and pantry.",
  images: imagesSet,
  amenities: ["High Speed Internet", "Conference Hall", "Power Backup"],
  mapLocation: { lat: 28.63, lng: 77.36 },
  intent: "medium",
  postedOn: "yesterday",
  postedAt: "2025-09-20T09:00:00Z",
  contact: {
    name: "Amit Verma",
    phone: "+91 9811009988",
    email: "amit.verma@logixoffices.com",
    whatsapp: "https://wa.me/919811009988",
    scheduleVisitLink: "https://calendly.com/amit-office/visit"
  },
  highlights: ["Near Metro", "Fully Furnished", "IT/ITES Approved"],
  legalClearance: ["RERA Approved", "Commercial NOC"]
},
{
  id: 24,
  title: "Retail Shop in Sector 18 Noida",
  status: "Ready to Move",
  transaction: "Resale",
  furnishing: "Unfurnished",
  society: "Wave Mall",
  propertyType: "Shop",
  area: { builtUp: "600 sq.ft" },
  price: "₹1.5 Cr",
  carpetArea: "550 sq.ft",
  pricePerSqft: "₹25,000 / sq.ft",
  location: { city: "Noida", locality: "Sector 18", landmark: "Wave Mall Main Road" },
  carParking: "Basement Parking",
  description: "Prime retail shop with heavy footfall, near metro station.",
  images: imagesSet,
  amenities: ["Mall Facing", "CCTV", "Escalator"],
  mapLocation: { lat: 28.57, lng: 77.32 },
  intent: "high",
  postedOn: "today",
  postedAt: "2025-09-21T10:00:00Z",
  contact: {
    name: "Deepak Arora",
    phone: "+91 9876543212",
    email: "deepak.arora@noidashops.com",
    whatsapp: "https://wa.me/919876543212",
    scheduleVisitLink: "https://calendly.com/deepak-shop/visit"
  },
  highlights: ["Sector 18 hub", "High rental value", "Near Metro"],
  legalClearance: ["Clear Title", "RERA Approved"]
},
{
  id: 25,
  title: "Luxury Penthouse in Sector 93 Noida",
  status: "Under Construction",
  transaction: "New Property",
  furnishing: "Semi-Furnished",
  society: "Supernova Spira",
  propertyType: "Penthouse",
  bhk: "4 BHK",
  area: { builtUp: "4000 sq.ft" },
  price: "₹7 Cr",
  carpetArea: "3600 sq.ft",
  pricePerSqft: "₹17,500 / sq.ft",
  location: { city: "Noida", locality: "Sector 93", landmark: "Near Noida Expressway" },
  carParking: "3 Covered",
  description: "High-rise penthouse with private terrace and city views.",
  images: imagesSet,
  amenities: ["Sky Lounge", "Gym", "Infinity Pool"],
  mapLocation: { lat: 28.55, lng: 77.38 },
  intent: "high",
  postedOn: "this week",
  postedAt: "2025-09-17T15:30:00Z",
  contact: {
    name: "Sanjay Mehta",
    phone: "+91 9811223344",
    email: "sanjay.mehta@supernovapenthouses.com",
    whatsapp: "https://wa.me/919811223344",
    scheduleVisitLink: "https://calendly.com/sanjay-penthouse/visit"
  },
  highlights: ["Skyline views", "Luxury fittings", "Expressway connectivity"],
  legalClearance: ["RERA Approved", "Clear Title"]
},
{
  id: 26,
  title: "Industrial Land in Noida Phase-II",
  status: "Ready to Move",
  transaction: "Resale",
  furnishing: "Unfurnished",
  society: "Industrial Plot Zone",
  propertyType: "Industrial Land",
  area: { builtUp: "1 Acre" },
  price: "₹12 Cr",
  carpetArea: "N/A",
  pricePerSqft: "₹27,500 / sq.yd",
  location: { city: "Noida", locality: "Phase-II", landmark: "Near Dadri Road" },
  carParking: "Truck Parking",
  description: "Industrial land suitable for manufacturing and warehousing.",
  images: imagesSet03,
  amenities: ["Wide Road", "Electricity Supply", "Water Connection"],
  mapLocation: { lat: 28.6, lng: 77.4 },
  intent: "medium",
  postedOn: "yesterday",
  postedAt: "2025-09-20T08:30:00Z",
  contact: {
    name: "Manoj Singh",
    phone: "+91 9811555566",
    email: "manoj.singh@noidaindustrial.com",
    whatsapp: "https://wa.me/919811555566",
    scheduleVisitLink: "https://calendly.com/manoj-land/visit"
  },
  highlights: ["Wide approach road", "Industrial approved", "Prime location"],
  legalClearance: ["Industrial NOC", "RERA Approved"]
},
{
  id: 27,
  title: "Serviced Hotel Apartment in Noida Sector 44",
  status: "Ready to Move",
  transaction: "New Property",
  furnishing: "Furnished",
  society: "Omaxe Residency",
  propertyType: "Hotel Apartment",
  bhk: "Studio",
  area: { builtUp: "650 sq.ft" },
  price: "₹80 Lac",
  carpetArea: "580 sq.ft",
  pricePerSqft: "₹12,308 / sq.ft",
  location: { city: "Noida", locality: "Sector 44", landmark: "Near Botanical Garden Metro" },
  carParking: "1 Covered",
  description: "Fully furnished serviced apartment with rental returns.",
  images: imagesSet,
  amenities: ["Housekeeping", "Restaurant", "Swimming Pool"],
  mapLocation: { lat: 28.56, lng: 77.34 },
  intent: "high",
  postedOn: "this week",
  postedAt: "2025-09-19T14:30:00Z",
  contact: {
    name: "Nidhi Sharma",
    phone: "+91 9811778899",
    email: "nidhi.sharma@omaxehotels.com",
    whatsapp: "https://wa.me/919811778899",
    scheduleVisitLink: "https://calendly.com/nidhi-hotel/visit"
  },
  highlights: ["Serviced apartment", "High rental yield", "Metro connectivity"],
  legalClearance: ["RERA Approved", "Hotel License"]
},
{
  id: 28,
  title: "Townhouse in Noida Sector 133",
  status: "Under Construction",
  transaction: "New Property",
  furnishing: "Semi-Furnished",
  society: "Eldeco Estate",
  propertyType: "Townhouse",
  bhk: "4 BHK",
  area: { builtUp: "2500 sq.ft" },
  price: "₹2.5 Cr",
  carpetArea: "2200 sq.ft",
  pricePerSqft: "₹10,000 / sq.ft",
  location: { city: "Noida", locality: "Sector 133", landmark: "Near Expressway" },
  carParking: "2 Covered",
  description: "Elegant townhouse in gated community with club facilities.",
  images: imagesSet03,
  amenities: ["Clubhouse", "Park", "Children Play Area"],
  mapLocation: { lat: 28.54, lng: 77.39 },
  intent: "medium",
  postedOn: "today",
  postedAt: "2025-09-21T09:30:00Z",
  contact: {
    name: "Vikas Anand",
    phone: "+91 9811888999",
    email: "vikas.anand@eldecohomes.com",
    whatsapp: "https://wa.me/919811888999",
    scheduleVisitLink: "https://calendly.com/vikas-townhouse/visit"
  },
  highlights: ["Expressway location", "Modern layout", "Family friendly"],
  legalClearance: ["RERA Approved", "Bank Loan Available"]
},
{
  id: 29,
  title: "Warehouse in Noida Sector 80",
  status: "Ready to Move",
  transaction: "Resale",
  furnishing: "Unfurnished",
  society: "Industrial Hub",
  propertyType: "Warehouse",
  area: { builtUp: "25,000 sq.ft" },
  price: "₹18 Cr",
  carpetArea: "N/A",
  pricePerSqft: "₹7,200 / sq.ft",
  location: { city: "Noida", locality: "Sector 80", landmark: "Near NSEZ" },
  carParking: "Truck Parking",
  description: "Spacious warehouse with high ceiling and docking bays.",
  images: imagesSet,
  amenities: ["Loading Docks", "CCTV", "Power Backup"],
  mapLocation: { lat: 28.58, lng: 77.37 },
  intent: "medium",
  postedOn: "yesterday",
  postedAt: "2025-09-20T11:00:00Z",
  contact: {
    name: "Rajeev Khanna",
    phone: "+91 9811999911",
    email: "rajeev.khanna@noidawarehouses.com",
    whatsapp: "https://wa.me/919811999911",
    scheduleVisitLink: "https://calendly.com/rajeev-warehouse/visit"
  },
  highlights: ["NSEZ proximity", "Ready warehouse", "Industrial approved"],
  legalClearance: ["RERA Approved", "Commercial NOC"]
},
{
  id: 30,
  title: "Mixed Use Land in Noida Sector 75",
  status: "Ready to Move",
  transaction: "Resale",
  furnishing: "Unfurnished",
  society: "Mixed Development Plot",
  propertyType: "Mixed Use Land",
  area: { builtUp: "2 Acres" },
  price: "₹30 Cr",
  carpetArea: "N/A",
  pricePerSqft: "₹13,636 / sq.yd",
  location: { city: "Noida", locality: "Sector 75", landmark: "Near Metro Station" },
  carParking: "Open Parking",
  description: "Mixed use land suitable for commercial and residential development.",
  images: imagesSet,
  amenities: ["Wide Road", "Power Supply", "Metro Connectivity"],
  mapLocation: { lat: 28.57, lng: 77.36 },
  intent: "high",
  postedOn: "this week",
  postedAt: "2025-09-18T16:00:00Z",
  contact: {
    name: "Alok Bansal",
    phone: "+91 9811333344",
    email: "alok.bansal@noidaproperties.com",
    whatsapp: "https://wa.me/919811333344",
    scheduleVisitLink: "https://calendly.com/alok-mixedland/visit"
  },
  highlights: ["Mixed development", "Prime sector", "Near metro"],
  legalClearance: ["RERA Approved", "Clear Title"]
},

// ---------- Gurgaon (31–40) ----------
{
  id: 31,
  title: "Luxury 4 BHK Apartment in DLF Phase 5, Gurgaon",
  status: "Ready to Move",
  transaction: "New Property",
  furnishing: "Furnished",
  society: "DLF The Crest",
  propertyType: "Apartment",
  bhk: "4 BHK",
  area: { builtUp: "3500 sq.ft" },
  price: "₹6 Cr",
  carpetArea: "3100 sq.ft",
  pricePerSqft: "₹17,142 / sq.ft",
  location: { city: "Gurgaon", locality: "DLF Phase 5", landmark: "Golf Course Road" },
  carParking: "3 Covered",
  description: "Luxury high-rise apartment with modern amenities and city views.",
  images: imagesSet,
  amenities: ["Swimming Pool", "Clubhouse", "Spa", "24x7 Security"],
  mapLocation: { lat: 28.45, lng: 77.09 },
  intent: "high",
  postedOn: "today",
  postedAt: "2025-09-21T10:30:00Z",
  contact: {
    name: "Ankit Sharma",
    phone: "+91 9811556677",
    email: "ankit.sharma@dlfhomes.com",
    whatsapp: "https://wa.me/919811556677",
    scheduleVisitLink: "https://calendly.com/ankit-dlf/visit"
  },
  highlights: ["Golf Course Road", "Luxury tower", "High rental demand"],
  legalClearance: ["RERA Approved", "Bank Loan Available"]
},
{
  id: 32,
  title: "Independent Villa in Sector 57, Gurgaon",
  status: "Ready to Move",
  transaction: "Resale",
  furnishing: "Semi-Furnished",
  society: "Vipul World",
  propertyType: "Villa",
  bhk: "5 BHK",
  area: { builtUp: "6000 sq.ft" },
  price: "₹8.5 Cr",
  carpetArea: "5400 sq.ft",
  pricePerSqft: "₹14,167 / sq.ft",
  location: { city: "Gurgaon", locality: "Sector 57", landmark: "Golf Course Extension" },
  carParking: "4 Covered",
  description: "Spacious independent villa with landscaped garden and modular kitchen.",
  images: imagesSet03,
  amenities: ["Private Garden", "Terrace", "Security"],
  mapLocation: { lat: 28.42, lng: 77.08 },
  intent: "high",
  postedOn: "this week",
  postedAt: "2025-09-18T14:00:00Z",
  contact: {
    name: "Ritika Malhotra",
    phone: "+91 9811777788",
    email: "ritika.malhotra@vipulhomes.com",
    whatsapp: "https://wa.me/919811777788",
    scheduleVisitLink: "https://calendly.com/ritika-villa/visit"
  },
  highlights: ["Golf Extension Road", "Independent villa", "Luxury interiors"],
  legalClearance: ["RERA Approved", "Clear Title"]
},
{
  id: 33,
  title: "Office Space in Cyber City, Gurgaon",
  status: "Ready to Move",
  transaction: "Resale",
  furnishing: "Furnished",
  society: "Cyber Hub Towers",
  propertyType: "Office",
  area: { builtUp: "5000 sq.ft" },
  price: "₹6 Cr",
  carpetArea: "4700 sq.ft",
  pricePerSqft: "₹12,000 / sq.ft",
  location: { city: "Gurgaon", locality: "Cyber City", landmark: "Near DLF Cyber Hub" },
  carParking: "6 Reserved",
  description: "Furnished IT/ITES office with 70 workstations, cabins & conference rooms.",
  images: imagesSet,
  amenities: ["High Speed Internet", "Conference Hall", "Power Backup"],
  mapLocation: { lat: 28.49, lng: 77.09 },
  intent: "high",
  postedOn: "yesterday",
  postedAt: "2025-09-20T11:15:00Z",
  contact: {
    name: "Naveen Mehta",
    phone: "+91 9811666677",
    email: "naveen.mehta@cyberhuboffices.com",
    whatsapp: "https://wa.me/919811666677",
    scheduleVisitLink: "https://calendly.com/naveen-office/visit"
  },
  highlights: ["DLF Cyber Hub", "IT approved", "Prime commercial hub"],
  legalClearance: ["RERA Approved", "Commercial NOC"]
},
{
  id: 34,
  title: "Luxury Penthouse in Gurgaon Sector 54",
  status: "Under Construction",
  transaction: "New Property",
  furnishing: "Semi-Furnished",
  society: "The Aralias",
  propertyType: "Penthouse",
  bhk: "5 BHK",
  area: { builtUp: "7000 sq.ft" },
  price: "₹20 Cr",
  carpetArea: "6500 sq.ft",
  pricePerSqft: "₹28,571 / sq.ft",
  location: { city: "Gurgaon", locality: "Sector 54", landmark: "Golf Course Road" },
  carParking: "5 Covered",
  description: "Ultra-luxury penthouse with golf course views and private deck.",
  images: imagesSet,
  amenities: ["Infinity Pool", "Gym", "Concierge", "Sky Lounge"],
  mapLocation: { lat: 28.45, lng: 77.1 },
  intent: "high",
  postedOn: "today",
  postedAt: "2025-09-21T12:00:00Z",
  contact: {
    name: "Kunal Khanna",
    phone: "+91 9811999988",
    email: "kunal.khanna@araliasluxury.com",
    whatsapp: "https://wa.me/919811999988",
    scheduleVisitLink: "https://calendly.com/kunal-penthouse/visit"
  },
  highlights: ["Golf Course view", "Ultra-luxury", "DLF Aralias"],
  legalClearance: ["RERA Approved", "OC Applied"]
},
{
  id: 35,
  title: "Retail Shop in MG Road, Gurgaon",
  status: "Ready to Move",
  transaction: "Resale",
  furnishing: "Unfurnished",
  society: "MGF Metropolitan Mall",
  propertyType: "Shop",
  area: { builtUp: "800 sq.ft" },
  price: "₹2.2 Cr",
  carpetArea: "750 sq.ft",
  pricePerSqft: "₹27,500 / sq.ft",
  location: { city: "Gurgaon", locality: "MG Road", landmark: "Near MG Metro Station" },
  carParking: "Basement Parking",
  description: "Retail shop in prime mall with heavy footfall.",
  images: imagesSet,
  amenities: ["Mall Facing", "Escalator", "Security"],
  mapLocation: { lat: 28.47, lng: 77.1 },
  intent: "medium",
  postedOn: "this week",
  postedAt: "2025-09-19T15:00:00Z",
  contact: {
    name: "Suresh Bhatia",
    phone: "+91 9811222211",
    email: "suresh.bhatia@gurgaonshops.com",
    whatsapp: "https://wa.me/919811222211",
    scheduleVisitLink: "https://calendly.com/suresh-shop/visit"
  },
  highlights: ["Mall location", "High rental demand", "Metro connectivity"],
  legalClearance: ["RERA Approved", "Shop License"]
},
{
  id: 36,
  title: "Warehouse in Gurgaon Sector 37",
  status: "Ready to Move",
  transaction: "Resale",
  furnishing: "Unfurnished",
  society: "Industrial Hub",
  propertyType: "Warehouse",
  area: { builtUp: "40,000 sq.ft" },
  price: "₹28 Cr",
  carpetArea: "N/A",
  pricePerSqft: "₹7,000 / sq.ft",
  location: { city: "Gurgaon", locality: "Sector 37", landmark: "Near Hero Honda Chowk" },
  carParking: "Truck Parking",
  description: "Large warehouse with docking bays, suitable for logistics.",
  images: imagesSet,
  amenities: ["CCTV", "Power Backup", "Wide Roads"],
  mapLocation: { lat: 28.45, lng: 77.03 },
  intent: "medium",
  postedOn: "yesterday",
  postedAt: "2025-09-20T13:30:00Z",
  contact: {
    name: "Mahesh Gupta",
    phone: "+91 9811444455",
    email: "mahesh.gupta@gurgaonwarehouses.com",
    whatsapp: "https://wa.me/919811444455",
    scheduleVisitLink: "https://calendly.com/mahesh-warehouse/visit"
  },
  highlights: ["NH-8 proximity", "Ready warehouse", "Logistics hub"],
  legalClearance: ["RERA Approved", "Commercial NOC"]
},
{
  id: 37,
  title: "Townhouse in Gurgaon Sector 52",
  status: "Under Construction",
  transaction: "New Property",
  furnishing: "Semi-Furnished",
  society: "Vatika Townhomes",
  propertyType: "Townhouse",
  bhk: "4 BHK",
  area: { builtUp: "2800 sq.ft" },
  price: "₹2.8 Cr",
  carpetArea: "2500 sq.ft",
  pricePerSqft: "₹10,000 / sq.ft",
  location: { city: "Gurgaon", locality: "Sector 52", landmark: "Near Artemis Hospital" },
  carParking: "2 Covered",
  description: "Elegant townhouse in gated society with landscaped gardens.",
  images: imagesSet,
  amenities: ["Clubhouse", "Park", "Children Play Area"],
  mapLocation: { lat: 28.43, lng: 77.07 },
  intent: "medium",
  postedOn: "today",
  postedAt: "2025-09-21T09:45:00Z",
  contact: {
    name: "Rajiv Arora",
    phone: "+91 9811888800",
    email: "rajiv.arora@vatikahomes.com",
    whatsapp: "https://wa.me/919811888800",
    scheduleVisitLink: "https://calendly.com/rajiv-townhouse/visit"
  },
  highlights: ["Gated community", "Modern townhouse", "Prime location"],
  legalClearance: ["RERA Approved", "Bank Loan Available"]
},
{
  id: 38,
  title: "Hotel Apartment in Gurgaon Sector 29",
  status: "Ready to Move",
  transaction: "New Property",
  furnishing: "Furnished",
  society: "Leisure Suites",
  propertyType: "Hotel Apartment",
  bhk: "Studio",
  area: { builtUp: "700 sq.ft" },
  price: "₹1.1 Cr",
  carpetArea: "650 sq.ft",
  pricePerSqft: "₹15,714 / sq.ft",
  location: { city: "Gurgaon", locality: "Sector 29", landmark: "Near HUDA City Metro" },
  carParking: "1 Covered",
  description: "Fully serviced hotel apartment ideal for business travelers.",
  images: imagesSet,
  amenities: ["Housekeeping", "Restaurant", "Gym"],
  mapLocation: { lat: 28.47, lng: 77.05 },
  intent: "high",
  postedOn: "this week",
  postedAt: "2025-09-18T16:30:00Z",
  contact: {
    name: "Simran Kaur",
    phone: "+91 9811992200",
    email: "simran.kaur@gurgaonhotelhomes.com",
    whatsapp: "https://wa.me/919811992200",
    scheduleVisitLink: "https://calendly.com/simran-hotel/visit"
  },
  highlights: ["Near Metro", "Serviced apartment", "Rental returns"],
  legalClearance: ["RERA Approved", "Hotel License"]
},
{
  id: 39,
  title: "Industrial Land in IMT Manesar, Gurgaon",
  status: "Ready to Move",
  transaction: "Resale",
  furnishing: "Unfurnished",
  society: "IMT Industrial Zone",
  propertyType: "Industrial Land",
  area: { builtUp: "2 Acres" },
  price: "₹40 Cr",
  carpetArea: "N/A",
  pricePerSqft: "₹20,000 / sq.yd",
  location: { city: "Gurgaon", locality: "IMT Manesar", landmark: "NH-8 Connectivity" },
  carParking: "Open Parking",
  description: "Industrial land suitable for factories and warehouses in Manesar hub.",
  images: imagesSet,
  amenities: ["Wide Road", "Electricity", "Water Connection"],
  mapLocation: { lat: 28.36, lng: 76.93 },
  intent: "medium",
  postedOn: "yesterday",
  postedAt: "2025-09-20T08:30:00Z",
  contact: {
    name: "Sunil Yadav",
    phone: "+91 9811777700",
    email: "sunil.yadav@imtmanesar.com",
    whatsapp: "https://wa.me/919811777700",
    scheduleVisitLink: "https://calendly.com/sunil-land/visit"
  },
  highlights: ["IMT Manesar", "Industrial hub", "NH-8 proximity"],
  legalClearance: ["Industrial NOC", "RERA Approved"]
},
{
  id: 40,
  title: "Mixed Use Land in Gurgaon Sector 71",
  status: "Ready to Move",
  transaction: "Resale",
  furnishing: "Unfurnished",
  society: "Commercial Development Plot",
  propertyType: "Mixed Use Land",
  area: { builtUp: "3 Acres" },
  price: "₹60 Cr",
  carpetArea: "N/A",
  pricePerSqft: "₹20,000 / sq.yd",
  location: { city: "Gurgaon", locality: "Sector 71", landmark: "Sohna Road" },
  carParking: "Open Parking",
  description: "Prime mixed use plot for commercial & residential development.",
  images: imagesSet,
  amenities: ["Wide Road", "Sewage", "Electricity"],
  mapLocation: { lat: 28.41, lng: 77.06 },
  intent: "high",
  postedOn: "this week",
  postedAt: "2025-09-19T12:15:00Z",
  contact: {
    name: "Aditya Jain",
    phone: "+91 9811333399",
    email: "aditya.jain@gurgaonlands.com",
    whatsapp: "https://wa.me/919811333399",
    scheduleVisitLink: "https://calendly.com/aditya-mixedland/visit"
  },
  highlights: ["Sohna Road", "Mixed development", "Prime sector"],
  legalClearance: ["RERA Approved", "Clear Title"]
},

// ---------- Delhi (41–50) ----------
{
  id: 41,
  title: "3 BHK Apartment in South Delhi, Greater Kailash II",
  status: "Ready to Move",
  transaction: "Resale",
  furnishing: "Furnished",
  society: "GK-II Apartments",
  propertyType: "Apartment",
  bhk: "3 BHK",
  area: { builtUp: "1800 sq.ft" },
  price: "₹3.2 Cr",
  carpetArea: "1600 sq.ft",
  pricePerSqft: "₹17,778 / sq.ft",
  location: { city: "Delhi", locality: "Greater Kailash II", landmark: "M-Block Market" },
  carParking: "2 Covered",
  description: "Luxury 3 BHK apartment in South Delhi’s prime location.",
  images: imagesSet,
  amenities: ["Lift", "Security", "Park", "Power Backup"],
  mapLocation: { lat: 28.54, lng: 77.24 },
  intent: "high",
  postedOn: "today",
  postedAt: "2025-09-21T10:30:00Z",
  contact: {
    name: "Rohit Mehra",
    phone: "+91 9811122233",
    email: "rohit.mehra@delhihomes.com",
    whatsapp: "https://wa.me/919811122233",
    scheduleVisitLink: "https://calendly.com/rohit-gk/visit"
  },
  highlights: ["Prime South Delhi location", "Near market", "Well-maintained society"],
  legalClearance: ["RERA Approved", "Clear Title"]
},
{
  id: 42,
  title: "Independent Bungalow in Vasant Vihar",
  status: "Ready to Move",
  transaction: "Resale",
  furnishing: "Furnished",
  society: "Vasant Vihar Enclave",
  propertyType: "Villa",
  bhk: "6 BHK",
  area: { builtUp: "9000 sq.ft" },
  price: "₹28 Cr",
  carpetArea: "8500 sq.ft",
  pricePerSqft: "₹31,111 / sq.ft",
  location: { city: "Delhi", locality: "Vasant Vihar", landmark: "Embassy Area" },
  carParking: "6 Covered",
  description: "Ultra-luxury bungalow in Vasant Vihar with private garden.",
  images: imagesSet,
  amenities: ["Garden", "Terrace", "24x7 Security"],
  mapLocation: { lat: 28.55, lng: 77.15 },
  intent: "high",
  postedOn: "yesterday",
  postedAt: "2025-09-20T15:00:00Z",
  contact: {
    name: "Anita Kapoor",
    phone: "+91 9811456789",
    email: "anita.kapoor@luxuryvillas.com",
    whatsapp: "https://wa.me/919811456789",
    scheduleVisitLink: "https://calendly.com/anita-villa/visit"
  },
  highlights: ["Embassy area", "Independent house", "Luxury construction"],
  legalClearance: ["RERA Approved", "Bank Loan Available"]
},
{
  id: 43,
  title: "Commercial Office in Connaught Place",
  status: "Ready to Move",
  transaction: "Resale",
  furnishing: "Furnished",
  society: "CP Business Towers",
  propertyType: "Office",
  area: { builtUp: "6000 sq.ft" },
  price: "₹14 Cr",
  carpetArea: "5700 sq.ft",
  pricePerSqft: "₹23,333 / sq.ft",
  location: { city: "Delhi", locality: "Connaught Place", landmark: "Near Rajiv Chowk Metro" },
  carParking: "8 Reserved",
  description: "Furnished Grade-A office in the heart of Connaught Place.",
  images: imagesSet,
  amenities: ["Conference Rooms", "Power Backup", "High Speed Internet"],
  mapLocation: { lat: 28.63, lng: 77.22 },
  intent: "high",
  postedOn: "this week",
  postedAt: "2025-09-18T11:30:00Z",
  contact: {
    name: "Arvind Khanna",
    phone: "+91 9811334455",
    email: "arvind.khanna@cpoffices.com",
    whatsapp: "https://wa.me/919811334455",
    scheduleVisitLink: "https://calendly.com/arvind-office/visit"
  },
  highlights: ["Connaught Place", "Grade A building", "Metro connectivity"],
  legalClearance: ["Commercial NOC", "RERA Approved"]
},
{
  id: 44,
  title: "Retail Shop in Karol Bagh Market",
  status: "Ready to Move",
  transaction: "Resale",
  furnishing: "Unfurnished",
  society: "Ajmal Khan Road Shops",
  propertyType: "Shop",
  area: { builtUp: "1000 sq.ft" },
  price: "₹3 Cr",
  carpetArea: "950 sq.ft",
  pricePerSqft: "₹30,000 / sq.ft",
  location: { city: "Delhi", locality: "Karol Bagh", landmark: "Ajmal Khan Road" },
  carParking: "Street Parking",
  description: "Prime retail shop in Karol Bagh market area.",
  images: imagesSet,
  amenities: ["High Footfall", "Security"],
  mapLocation: { lat: 28.65, lng: 77.19 },
  intent: "medium",
  postedOn: "today",
  postedAt: "2025-09-21T14:00:00Z",
  contact: {
    name: "Mohit Sethi",
    phone: "+91 9811999888",
    email: "mohit.sethi@delhishops.com",
    whatsapp: "https://wa.me/919811999888",
    scheduleVisitLink: "https://calendly.com/mohit-shop/visit"
  },
  highlights: ["Karol Bagh Market", "Heavy footfall", "Prime retail space"],
  legalClearance: ["Shop License", "RERA Approved"]
},
{
  id: 45,
  title: "Penthouse in Hauz Khas",
  status: "Under Construction",
  transaction: "New Property",
  furnishing: "Semi-Furnished",
  society: "Greenview Heights",
  propertyType: "Penthouse",
  bhk: "4 BHK",
  area: { builtUp: "4500 sq.ft" },
  price: "₹9.5 Cr",
  carpetArea: "4200 sq.ft",
  pricePerSqft: "₹21,111 / sq.ft",
  location: { city: "Delhi", locality: "Hauz Khas", landmark: "Near Deer Park" },
  carParking: "3 Covered",
  description: "Modern penthouse with terrace garden overlooking Deer Park.",
  images: imagesSet,
  amenities: ["Terrace Garden", "Gym", "Clubhouse"],
  mapLocation: { lat: 28.55, lng: 77.2 },
  intent: "high",
  postedOn: "yesterday",
  postedAt: "2025-09-20T18:00:00Z",
  contact: {
    name: "Sanjay Verma",
    phone: "+91 9811223344",
    email: "sanjay.verma@delhipenthouses.com",
    whatsapp: "https://wa.me/919811223344",
    scheduleVisitLink: "https://calendly.com/sanjay-penthouse/visit"
  },
  highlights: ["Deer Park view", "Luxury interiors", "Modern design"],
  legalClearance: ["RERA Approved", "OC Pending"]
},
{
  id: 46,
  title: "Hotel Apartment in Aerocity, Delhi",
  status: "Ready to Move",
  transaction: "New Property",
  furnishing: "Furnished",
  society: "Aerocity Residences",
  propertyType: "Hotel Apartment",
  bhk: "Studio",
  area: { builtUp: "850 sq.ft" },
  price: "₹1.7 Cr",
  carpetArea: "800 sq.ft",
  pricePerSqft: "₹20,000 / sq.ft",
  location: { city: "Delhi", locality: "Aerocity", landmark: "Near IGI Airport" },
  carParking: "1 Covered",
  description: "Fully serviced hotel apartment with rental income option.",
  images: imagesSet,
  amenities: ["Housekeeping", "Gym", "Restaurant"],
  mapLocation: { lat: 28.55, lng: 77.08 },
  intent: "high",
  postedOn: "this week",
  postedAt: "2025-09-17T13:30:00Z",
  contact: {
    name: "Priya Singh",
    phone: "+91 9811999000",
    email: "priya.singh@aerocityhomes.com",
    whatsapp: "https://wa.me/919811999000",
    scheduleVisitLink: "https://calendly.com/priya-hotelapt/visit"
  },
  highlights: ["Near IGI Airport", "Serviced apartments", "Rental returns"],
  legalClearance: ["Hotel License", "RERA Approved"]
},
{
  id: 47,
  title: "Land for Development in Dwarka Sector 21",
  status: "Ready to Move",
  transaction: "Resale",
  furnishing: "Unfurnished",
  society: "Dwarka Development Zone",
  propertyType: "Land",
  area: { builtUp: "1 Acre" },
  price: "₹55 Cr",
  carpetArea: "N/A",
  pricePerSqft: "₹13,500 / sq.yd",
  location: { city: "Delhi", locality: "Dwarka Sector 21", landmark: "Near Airport Express Metro" },
  carParking: "Open Parking",
  description: "Prime land parcel suitable for residential and commercial development.",
  images: imagesSet,
  amenities: ["Wide Road Access", "Electricity", "Water Connection"],
  mapLocation: { lat: 28.56, lng: 77.06 },
  intent: "high",
  postedOn: "today",
  postedAt: "2025-09-21T09:45:00Z",
  contact: {
    name: "Deepak Yadav",
    phone: "+91 9811333000",
    email: "deepak.yadav@delhilands.com",
    whatsapp: "https://wa.me/919811333000",
    scheduleVisitLink: "https://calendly.com/deepak-land/visit"
  },
  highlights: ["Dwarka Express Metro", "1 Acre plot", "Prime location"],
  legalClearance: ["RERA Approved", "Clear Title"]
},
{
  id: 48,
  title: "Warehouse in Mundka Industrial Area",
  status: "Ready to Move",
  transaction: "Resale",
  furnishing: "Unfurnished",
  society: "Mundka Industrial Hub",
  propertyType: "Warehouse",
  area: { builtUp: "25,000 sq.ft" },
  price: "₹15 Cr",
  carpetArea: "N/A",
  pricePerSqft: "₹6,000 / sq.ft",
  location: { city: "Delhi", locality: "Mundka", landmark: "Near Metro Depot" },
  carParking: "Truck Parking",
  description: "Spacious warehouse with high ceilings and easy transport access.",
  images: imagesSet,
  amenities: ["Loading Bays", "Power Backup", "Wide Road"],
  mapLocation: { lat: 28.68, lng: 77.05 },
  intent: "medium",
  postedOn: "yesterday",
  postedAt: "2025-09-20T16:30:00Z",
  contact: {
    name: "Harish Patel",
    phone: "+91 9811666000",
    email: "harish.patel@delhiwarehouses.com",
    whatsapp: "https://wa.me/919811666000",
    scheduleVisitLink: "https://calendly.com/harish-warehouse/visit"
  },
  highlights: ["Industrial hub", "Near Metro", "High storage capacity"],
  legalClearance: ["Industrial NOC", "RERA Approved"]
},
{
  id: 49,
  title: "Mixed Use Building in Lajpat Nagar",
  status: "Ready to Move",
  transaction: "Resale",
  furnishing: "Semi-Furnished",
  society: "Central Market Complex",
  propertyType: "Building",
  area: { builtUp: "10,000 sq.ft" },
  price: "₹40 Cr",
  carpetArea: "9500 sq.ft",
  pricePerSqft: "₹40,000 / sq.ft",
  location: { city: "Delhi", locality: "Lajpat Nagar", landmark: "Central Market" },
  carParking: "Basement Parking",
  description: "Full building with retail shops and office floors in Lajpat Nagar.",
  images: imagesSet,
  amenities: ["Lift", "Power Backup", "Security"],
  mapLocation: { lat: 28.57, lng: 77.25 },
  intent: "high",
  postedOn: "this week",
  postedAt: "2025-09-19T14:00:00Z",
  contact: {
    name: "Ashok Jain",
    phone: "+91 9811444000",
    email: "ashok.jain@delhibuildings.com",
    whatsapp: "https://wa.me/919811444000",
    scheduleVisitLink: "https://calendly.com/ashok-building/visit"
  },
  highlights: ["Central Market", "Retail + Office mix", "Prime business hub"],
  legalClearance: ["RERA Approved", "Commercial NOC"]
},
{
  id: 50,
  title: "Factory in Okhla Industrial Estate",
  status: "Ready to Move",
  transaction: "Resale",
  furnishing: "Unfurnished",
  society: "Okhla Phase II",
  propertyType: "Factory",
  area: { builtUp: "18,000 sq.ft" },
  price: "₹22 Cr",
  carpetArea: "17,000 sq.ft",
  pricePerSqft: "₹12,222 / sq.ft",
  location: { city: "Delhi", locality: "Okhla Industrial Area", landmark: "Phase II" },
  carParking: "Industrial Parking",
  description: "Ready factory space in Okhla Industrial Estate suitable for manufacturing.",
  images: imagesSet,
  amenities: ["Industrial Power", "Loading Area", "Security"],
  mapLocation: { lat: 28.55, lng: 77.29 },
  intent: "medium",
  postedOn: "today",
  postedAt: "2025-09-21T11:15:00Z",
  contact: {
    name: "Vinod Kumar",
    phone: "+91 9811888999",
    email: "vinod.kumar@okhlafactories.com",
    whatsapp: "https://wa.me/919811888999",
    scheduleVisitLink: "https://calendly.com/vinod-factory/visit"
  },
  highlights: ["Okhla Industrial Area", "Manufacturing hub", "Prime location"],
  legalClearance: ["Industrial NOC", "RERA Approved"]
},

// ---------- Bangalore (51–60) ----------
{
  id: 51,
  title: "2 BHK Apartment in Whitefield, Bangalore",
  status: "Ready to Move",
  transaction: "New Property",
  furnishing: "Semi-Furnished",
  society: "Prestige Lakeside Habitat",
  propertyType: "Apartment",
  bhk: "2 BHK",
  area: { builtUp: "1250 sq.ft" },
  price: "₹95 Lac",
  carpetArea: "1050 sq.ft",
  pricePerSqft: "₹7,600 / sq.ft",
  location: { city: "Bangalore", state: "Karnataka", locality: "Whitefield", landmark: "Near ITPL" },
  carParking: "1 Covered",
  description: "Modern 2 BHK apartment in gated community with top-class amenities.",
  images: imagesSet,
  amenities: ["Swimming Pool", "Gym", "Children’s Play Area", "Security"],
  mapLocation: { lat: 12.97, lng: 77.75 },
  intent: "high",
  postedOn: "today",
  postedAt: "2025-09-21T10:15:00Z",
  contact: {
    name: "Ravi Menon",
    phone: "+91 9811001111",
    email: "ravi.menon@prestigehomes.com",
    whatsapp: "https://wa.me/919811001111",
    scheduleVisitLink: "https://calendly.com/ravi-apartment/visit"
  },
  highlights: ["IT hub location", "Gated society", "Clubhouse"],
  legalClearance: ["RERA Approved", "Clear Title"]
},
{
  id: 52,
  title: "Luxury Villa in Sarjapur Road, Bangalore",
  status: "Under Construction",
  transaction: "New Property",
  furnishing: "Furnished",
  society: "Sobha Lifestyle",
  propertyType: "Villa",
  bhk: "5 BHK",
  area: { builtUp: "6000 sq.ft" },
  price: "₹7.5 Cr",
  carpetArea: "5500 sq.ft",
  pricePerSqft: "₹12,500 / sq.ft",
  location: { city: "Bangalore", state: "Karnataka", locality: "Sarjapur Road", landmark: "Close to Wipro HQ" },
  carParking: "4 Covered",
  description: "Premium villa with landscaped garden and luxury interiors.",
  images: imagesSet,
  amenities: ["Private Garden", "Pool", "Terrace", "24x7 Security"],
  mapLocation: { lat: 12.91, lng: 77.69 },
  intent: "high",
  postedOn: "yesterday",
  postedAt: "2025-09-20T17:00:00Z",
  contact: {
    name: "Sneha Rao",
    phone: "+91 9811222233",
    email: "sneha.rao@sobhavillas.com",
    whatsapp: "https://wa.me/919811222233",
    scheduleVisitLink: "https://calendly.com/sneha-villa/visit"
  },
  highlights: ["Luxury interiors", "Private garden", "Premium villa"],
  legalClearance: ["RERA Approved", "Bank Loan Available"]
},
{
  id: 53,
  title: "Office Space in MG Road, Bangalore",
  status: "Ready to Move",
  transaction: "Resale",
  furnishing: "Furnished",
  society: "UB City Tower",
  propertyType: "Office",
  area: { builtUp: "5000 sq.ft" },
  price: "₹9 Cr",
  carpetArea: "4700 sq.ft",
  pricePerSqft: "₹18,000 / sq.ft",
  location: { city: "Bangalore", state: "Karnataka", locality: "MG Road", landmark: "Near Cubbon Park" },
  carParking: "6 Reserved",
  description: "Grade-A office space with premium interiors in UB City.",
  images: imagesSet,
  amenities: ["Conference Rooms", "Valet Parking", "Security", "Power Backup"],
  mapLocation: { lat: 12.97, lng: 77.61 },
  intent: "high",
  postedOn: "this week",
  postedAt: "2025-09-18T11:00:00Z",
  contact: {
    name: "Arjun Reddy",
    phone: "+91 9811333344",
    email: "arjun.reddy@ubcityoffices.com",
    whatsapp: "https://wa.me/919811333344",
    scheduleVisitLink: "https://calendly.com/arjun-office/visit"
  },
  highlights: ["MG Road", "Premium office", "Metro connectivity"],
  legalClearance: ["Commercial NOC", "RERA Approved"]
},
{
  id: 54,
  title: "3 BHK Penthouse in Indiranagar",
  status: "Ready to Move",
  transaction: "Resale",
  furnishing: "Semi-Furnished",
  society: "Skyline Heights",
  propertyType: "Penthouse",
  bhk: "3 BHK",
  area: { builtUp: "3200 sq.ft" },
  price: "₹4.2 Cr",
  carpetArea: "3000 sq.ft",
  pricePerSqft: "₹13,125 / sq.ft",
  location: { city: "Bangalore", state: "Karnataka", locality: "Indiranagar", landmark: "100 Feet Road" },
  carParking: "2 Covered",
  description: "Spacious penthouse with terrace overlooking Indiranagar skyline.",
  images: imagesSet,
  amenities: ["Terrace", "Gym", "Lift", "24x7 Security"],
  mapLocation: { lat: 12.97, lng: 77.64 },
  intent: "high",
  postedOn: "today",
  postedAt: "2025-09-21T14:15:00Z",
  contact: {
    name: "Divya Shetty",
    phone: "+91 9811444455",
    email: "divya.shetty@skylinehomes.com",
    whatsapp: "https://wa.me/919811444455",
    scheduleVisitLink: "https://calendly.com/divya-penthouse/visit"
  },
  highlights: ["Indiranagar prime location", "Terrace view", "Modern amenities"],
  legalClearance: ["RERA Approved", "Clear Title"]
},
{
  id: 55,
  title: "Retail Shop in Commercial Street, Bangalore",
  status: "Ready to Move",
  transaction: "Resale",
  furnishing: "Unfurnished",
  society: "Commercial Street Market",
  propertyType: "Shop",
  area: { builtUp: "1200 sq.ft" },
  price: "₹2.5 Cr",
  carpetArea: "1150 sq.ft",
  pricePerSqft: "₹20,833 / sq.ft",
  location: { city: "Bangalore", state: "Karnataka", locality: "Commercial Street", landmark: "Brigade Road" },
  carParking: "Street Parking",
  description: "Prime retail shop in Bangalore’s busiest shopping hub.",
  images: imagesSet,
  amenities: ["High Footfall", "Security"],
  mapLocation: { lat: 12.98, lng: 77.61 },
  intent: "medium",
  postedOn: "yesterday",
  postedAt: "2025-09-20T13:30:00Z",
  contact: {
    name: "Imran Khan",
    phone: "+91 9811555566",
    email: "imran.khan@blrshops.com",
    whatsapp: "https://wa.me/919811555566",
    scheduleVisitLink: "https://calendly.com/imran-shop/visit"
  },
  highlights: ["Commercial Street", "Heavy footfall", "Prime retail"],
  legalClearance: ["Shop License", "RERA Approved"]
},
{
  id: 56,
  title: "Warehouse in Peenya Industrial Area, Bangalore",
  status: "Ready to Move",
  transaction: "Resale",
  furnishing: "Unfurnished",
  society: "Peenya Industrial Hub",
  propertyType: "Warehouse",
  area: { builtUp: "50,000 sq.ft" },
  price: "₹32 Cr",
  carpetArea: "N/A",
  pricePerSqft: "₹6,400 / sq.ft",
  location: { city: "Bangalore", state: "Karnataka", locality: "Peenya", landmark: "Near Tumkur Road" },
  carParking: "Truck Parking",
  description: "Large warehouse in Peenya with docking bays and wide road access.",
  images: imagesSet,
  amenities: ["Power Backup", "Security", "Loading Docks"],
  mapLocation: { lat: 13.02, lng: 77.52 },
  intent: "medium",
  postedOn: "this week",
  postedAt: "2025-09-18T15:00:00Z",
  contact: {
    name: "Nikhil Gowda",
    phone: "+91 9811666677",
    email: "nikhil.gowda@blrwarehouses.com",
    whatsapp: "https://wa.me/919811666677",
    scheduleVisitLink: "https://calendly.com/nikhil-warehouse/visit"
  },
  highlights: ["Peenya Industrial Hub", "Large warehouse", "Wide roads"],
  legalClearance: ["Industrial NOC", "RERA Approved"]
},
{
  id: 57,
  title: "Townhouse in Jayanagar, Bangalore",
  status: "Under Construction",
  transaction: "New Property",
  furnishing: "Semi-Furnished",
  society: "Greenwoods Enclave",
  propertyType: "Townhouse",
  bhk: "4 BHK",
  area: { builtUp: "2600 sq.ft" },
  price: "₹3 Cr",
  carpetArea: "2400 sq.ft",
  pricePerSqft: "₹11,538 / sq.ft",
  location: { city: "Bangalore", state: "Karnataka", locality: "Jayanagar", landmark: "Near Jain Temple" },
  carParking: "2 Covered",
  description: "Modern townhouse in peaceful Jayanagar with luxury finish.",
  images: imagesSet,
  amenities: ["Park", "Children’s Play Area", "Community Hall"],
  mapLocation: { lat: 12.93, lng: 77.58 },
  intent: "high",
  postedOn: "today",
  postedAt: "2025-09-21T09:00:00Z",
  contact: {
    name: "Karthik R",
    phone: "+91 9811777788",
    email: "karthik.r@townhouses.com",
    whatsapp: "https://wa.me/919811777788",
    scheduleVisitLink: "https://calendly.com/karthik-townhouse/visit"
  },
  highlights: ["Jayanagar peaceful area", "Modern design", "New construction"],
  legalClearance: ["RERA Approved", "Bank Loan Available"]
},
{
  id: 58,
  title: "Hotel Apartment in Electronic City, Bangalore",
  status: "Ready to Move",
  transaction: "New Property",
  furnishing: "Furnished",
  society: "Tech Park Suites",
  propertyType: "Hotel Apartment",
  bhk: "1 BHK",
  area: { builtUp: "900 sq.ft" },
  price: "₹1.25 Cr",
  carpetArea: "850 sq.ft",
  pricePerSqft: "₹13,889 / sq.ft",
  location: { city: "Bangalore", state: "Karnataka", locality: "Electronic City", landmark: "Infosys Campus" },
  carParking: "1 Covered",
  description: "Serviced hotel apartment perfect for IT professionals.",
  images: imagesSet,
  amenities: ["Housekeeping", "Gym", "Restaurant", "24x7 Security"],
  mapLocation: { lat: 12.84, lng: 77.66 },
  intent: "medium",
  postedOn: "yesterday",
  postedAt: "2025-09-20T12:45:00Z",
  contact: {
    name: "Megha N",
    phone: "+91 9811888899",
    email: "megha.n@techsuites.com",
    whatsapp: "https://wa.me/919811888899",
    scheduleVisitLink: "https://calendly.com/megha-hotelapt/visit"
  },
  highlights: ["Electronic City", "Serviced residence", "Rental income"],
  legalClearance: ["RERA Approved", "Hotel License"]
},
{
  id: 59,
  title: "Industrial Land in Devanahalli, Bangalore",
  status: "Ready to Move",
  transaction: "Resale",
  furnishing: "Unfurnished",
  society: "Devanahalli Industrial Zone",
  propertyType: "Industrial Land",
  area: { builtUp: "3 Acres" },
  price: "₹75 Cr",
  carpetArea: "N/A",
  pricePerSqft: "₹25,000 / sq.yd",
  location: { city: "Bangalore", state: "Karnataka", locality: "Devanahalli", landmark: "Near Airport" },
  carParking: "Open Parking",
  description: "Industrial land near Bangalore Airport ideal for warehouses/factories.",
  images: imagesSet,
  amenities: ["Wide Road", "Electricity", "Water Supply"],
  mapLocation: { lat: 13.12, lng: 77.7 },
  intent: "high",
  postedOn: "this week",
  postedAt: "2025-09-17T14:00:00Z",
  contact: {
    name: "Shankar Iyer",
    phone: "+91 9811999900",
    email: "shankar.iyer@blrlands.com",
    whatsapp: "https://wa.me/919811999900",
    scheduleVisitLink: "https://calendly.com/shankar-land/visit"
  },
  highlights: ["Near Airport", "Industrial land", "Prime zone"],
  legalClearance: ["Industrial NOC", "Clear Title"]
},
{
  id: 60,
  title: "Mixed Use Building in Koramangala, Bangalore",
  status: "Ready to Move",
  transaction: "Resale",
  furnishing: "Semi-Furnished",
  society: "Koramangala Plaza",
  propertyType: "Building",
  area: { builtUp: "15,000 sq.ft" },
  price: "₹50 Cr",
  carpetArea: "14,500 sq.ft",
  pricePerSqft: "₹33,333 / sq.ft",
  location: { city: "Bangalore", state: "Karnataka", locality: "Koramangala", landmark: "Sony World Signal" },
  carParking: "Basement Parking",
  description: "Full building with shops, offices and rooftop restaurant in Koramangala.",
  images: imagesSet,
  amenities: ["Lift", "Security", "Power Backup"],
  mapLocation: { lat: 12.93, lng: 77.62 },
  intent: "high",
  postedOn: "today",
  postedAt: "2025-09-21T15:30:00Z",
  contact: {
    name: "Vivek Rao",
    phone: "+91 9811333399",
    email: "vivek.rao@koramangalaproperties.com",
    whatsapp: "https://wa.me/919811333399",
    scheduleVisitLink: "https://calendly.com/vivek-building/visit"
  },
  highlights: ["Koramangala prime", "Mixed use building", "High rental yield"],
  legalClearance: ["RERA Approved", "Commercial NOC"]
},


// ---------- Hyderabad (61–70) ----------

{
  id: 61,
  title: "3 BHK Apartment in Gachibowli, Hyderabad",
  status: "Ready to Move",
  transaction: "New Property",
  furnishing: "Semi-Furnished",
  society: "My Home Avatar",
  propertyType: "Apartment",
  bhk: "3 BHK",
  area: { builtUp: "1650 sq.ft" },
  price: "₹1.35 Cr",
  carpetArea: "1450 sq.ft",
  pricePerSqft: "₹8,182 / sq.ft",
  location: { city: "Hyderabad", state: "Telangana", locality: "Gachibowli", landmark: "Near Wipro Circle" },
  carParking: "2 Covered",
  description: "Spacious 3 BHK apartment in IT hub with premium amenities.",
  images: imagesSet,
  amenities: ["Swimming Pool", "Gym", "Clubhouse", "24x7 Security"],
  mapLocation: { lat: 17.44, lng: 78.35 },
  intent: "high",
  postedOn: "today",
  postedAt: "2025-09-21T09:30:00Z",
  contact: {
    name: "Ramesh Kumar",
    phone: "+91 9811001112",
    email: "ramesh.kumar@hydbrokers.com",
    whatsapp: "https://wa.me/919811001112",
    scheduleVisitLink: "https://calendly.com/ramesh-apartment/visit"
  },
  highlights: ["IT hub location", "Premium amenities", "High rental demand"],
  legalClearance: ["RERA Approved", "Bank Loan Available"]
},
{
  id: 62,
  title: "Luxury Villa in Banjara Hills, Hyderabad",
  status: "Ready to Move",
  transaction: "Resale",
  furnishing: "Furnished",
  society: "Elite Villas",
  propertyType: "Villa",
  bhk: "5 BHK",
  area: { builtUp: "8000 sq.ft" },
  price: "₹18 Cr",
  carpetArea: "7600 sq.ft",
  pricePerSqft: "₹22,500 / sq.ft",
  location: { city: "Hyderabad", state: "Telangana", locality: "Banjara Hills", landmark: "Near Taj Krishna" },
  carParking: "6 Covered",
  description: "Ultra-luxury villa in Hyderabad’s most posh neighborhood.",
  images: imagesSet,
  amenities: ["Private Pool", "Garden", "Terrace", "Home Theatre"],
  mapLocation: { lat: 17.41, lng: 78.45 },
  intent: "high",
  postedOn: "yesterday",
  postedAt: "2025-09-20T18:00:00Z",
  contact: {
    name: "Sana Reddy",
    phone: "+91 9811333322",
    email: "sana.reddy@elitevillas.com",
    whatsapp: "https://wa.me/919811333322",
    scheduleVisitLink: "https://calendly.com/sana-villa/visit"
  },
  highlights: ["Luxury interiors", "Banjara Hills prime", "Private pool"],
  legalClearance: ["RERA Approved", "Clear Title"]
},
{
  id: 63,
  title: "Office Space in Hitech City, Hyderabad",
  status: "Under Construction",
  transaction: "New Property",
  furnishing: "Unfurnished",
  society: "Mindspace IT Park",
  propertyType: "Office",
  area: { builtUp: "20,000 sq.ft" },
  price: "₹32 Cr",
  carpetArea: "19,000 sq.ft",
  pricePerSqft: "₹16,000 / sq.ft",
  location: { city: "Hyderabad", state: "Telangana", locality: "Hitech City", landmark: "Near Cyber Towers" },
  carParking: "25 Covered",
  description: "Grade-A office space in the heart of Hyderabad’s IT district.",
  images: imagesSet,
  amenities: ["Power Backup", "Conference Rooms", "High-speed Lifts"],
  mapLocation: { lat: 17.45, lng: 78.38 },
  intent: "high",
  postedOn: "this week",
  postedAt: "2025-09-19T11:15:00Z",
  contact: {
    name: "Manoj Verma",
    phone: "+91 9811444411",
    email: "manoj.verma@itspaces.com",
    whatsapp: "https://wa.me/919811444411",
    scheduleVisitLink: "https://calendly.com/manoj-office/visit"
  },
  highlights: ["IT hub", "Grade-A office", "High ROI"],
  legalClearance: ["RERA Approved", "Commercial NOC"]
},
{
  id: 64,
  title: "4 BHK Penthouse in Jubilee Hills, Hyderabad",
  status: "Ready to Move",
  transaction: "Resale",
  furnishing: "Semi-Furnished",
  society: "Skyline Towers",
  propertyType: "Penthouse",
  bhk: "4 BHK",
  area: { builtUp: "5000 sq.ft" },
  price: "₹7.2 Cr",
  carpetArea: "4700 sq.ft",
  pricePerSqft: "₹14,400 / sq.ft",
  location: { city: "Hyderabad", state: "Telangana", locality: "Jubilee Hills", landmark: "Near Film Nagar" },
  carParking: "3 Covered",
  description: "Spacious penthouse with panoramic city views and terrace garden.",
  images: imagesSet,
  amenities: ["Terrace Garden", "Swimming Pool", "Clubhouse"],
  mapLocation: { lat: 17.42, lng: 78.41 },
  intent: "high",
  postedOn: "today",
  postedAt: "2025-09-21T13:00:00Z",
  contact: {
    name: "Aparna Rao",
    phone: "+91 9811555522",
    email: "aparna.rao@penthouses.com",
    whatsapp: "https://wa.me/919811555522",
    scheduleVisitLink: "https://calendly.com/aparna-penthouse/visit"
  },
  highlights: ["Panoramic view", "Luxury penthouse", "Jubilee Hills"],
  legalClearance: ["RERA Approved", "Bank Loan Available"]
},
{
  id: 65,
  title: "Retail Shop in Abids, Hyderabad",
  status: "Ready to Move",
  transaction: "Resale",
  furnishing: "Unfurnished",
  society: "Abids Commercial Plaza",
  propertyType: "Shop",
  area: { builtUp: "1500 sq.ft" },
  price: "₹2.8 Cr",
  carpetArea: "1450 sq.ft",
  pricePerSqft: "₹18,667 / sq.ft",
  location: { city: "Hyderabad", state: "Telangana", locality: "Abids", landmark: "Opposite GPO" },
  carParking: "Street Parking",
  description: "Prime retail shop in central Hyderabad’s shopping hub.",
  images: imagesSet,
  amenities: ["High Footfall", "Security"],
  mapLocation: { lat: 17.39, lng: 78.48 },
  intent: "medium",
  postedOn: "yesterday",
  postedAt: "2025-09-20T14:45:00Z",
  contact: {
    name: "Imtiyaz Khan",
    phone: "+91 9811666633",
    email: "imtiyaz.khan@hydbiz.com",
    whatsapp: "https://wa.me/919811666633",
    scheduleVisitLink: "https://calendly.com/imtiyaz-shop/visit"
  },
  highlights: ["Prime retail", "High visibility", "Abids central"],
  legalClearance: ["Shop License", "RERA Approved"]
},
{
  id: 66,
  title: "Warehouse in Shamshabad, Hyderabad",
  status: "Ready to Move",
  transaction: "Resale",
  furnishing: "Unfurnished",
  society: "Shamshabad Logistics Park",
  propertyType: "Warehouse",
  area: { builtUp: "80,000 sq.ft" },
  price: "₹50 Cr",
  carpetArea: "N/A",
  pricePerSqft: "₹6,250 / sq.ft",
  location: { city: "Hyderabad", state: "Telangana", locality: "Shamshabad", landmark: "Near Airport" },
  carParking: "Truck Parking",
  description: "Large warehouse near Hyderabad International Airport with logistics facilities.",
  images: imagesSet,
  amenities: ["Loading Bays", "CCTV", "Wide Road Access"],
  mapLocation: { lat: 17.25, lng: 78.4 },
  intent: "medium",
  postedOn: "this week",
  postedAt: "2025-09-18T12:00:00Z",
  contact: {
    name: "Naveen Reddy",
    phone: "+91 9811777744",
    email: "naveen.reddy@hydwarehouses.com",
    whatsapp: "https://wa.me/919811777744",
    scheduleVisitLink: "https://calendly.com/naveen-warehouse/visit"
  },
  highlights: ["Near airport", "Large space", "Logistics ready"],
  legalClearance: ["Industrial NOC", "RERA Approved"]
},
{
  id: 67,
  title: "Townhouse in Kondapur, Hyderabad",
  status: "Under Construction",
  transaction: "New Property",
  furnishing: "Semi-Furnished",
  society: "Greenwoods Enclave",
  propertyType: "Townhouse",
  bhk: "4 BHK",
  area: { builtUp: "2800 sq.ft" },
  price: "₹2.6 Cr",
  carpetArea: "2600 sq.ft",
  pricePerSqft: "₹9,286 / sq.ft",
  location: { city: "Hyderabad", state: "Telangana", locality: "Kondapur", landmark: "Near Botanical Garden" },
  carParking: "2 Covered",
  description: "Modern townhouse in Kondapur with premium finish.",
  images: imagesSet,
  amenities: ["Community Park", "Gym", "Children’s Play Area"],
  mapLocation: { lat: 17.46, lng: 78.37 },
  intent: "high",
  postedOn: "today",
  postedAt: "2025-09-21T08:00:00Z",
  contact: {
    name: "Krishna Rao",
    phone: "+91 9811888855",
    email: "krishna.rao@hydtownhouses.com",
    whatsapp: "https://wa.me/919811888855",
    scheduleVisitLink: "https://calendly.com/krishna-townhouse/visit"
  },
  highlights: ["Kondapur peaceful area", "Modern design", "New construction"],
  legalClearance: ["RERA Approved", "Bank Loan Available"]
},
{
  id: 68,
  title: "Hotel Apartment in Madhapur, Hyderabad",
  status: "Ready to Move",
  transaction: "New Property",
  furnishing: "Furnished",
  society: "Madhapur Suites",
  propertyType: "Hotel Apartment",
  bhk: "1 BHK",
  area: { builtUp: "950 sq.ft" },
  price: "₹1.1 Cr",
  carpetArea: "900 sq.ft",
  pricePerSqft: "₹11,579 / sq.ft",
  location: { city: "Hyderabad", state: "Telangana", locality: "Madhapur", landmark: "Near Inorbit Mall" },
  carParking: "1 Covered",
  description: "Serviced apartment perfect for IT professionals in Madhapur.",
  images: imagesSet,
  amenities: ["Housekeeping", "Restaurant", "Gym", "24x7 Security"],
  mapLocation: { lat: 17.44, lng: 78.39 },
  intent: "medium",
  postedOn: "yesterday",
  postedAt: "2025-09-20T10:30:00Z",
  contact: {
    name: "Anita Sharma",
    phone: "+91 9811999966",
    email: "anita.sharma@hydsuites.com",
    whatsapp: "https://wa.me/919811999966",
    scheduleVisitLink: "https://calendly.com/anita-hotelapt/visit"
  },
  highlights: ["Madhapur IT hub", "Serviced apartment", "Rental income"],
  legalClearance: ["RERA Approved", "Hotel License"]
},
{
  id: 69,
  title: "Industrial Land in Patancheru, Hyderabad",
  status: "Ready to Move",
  transaction: "Resale",
  furnishing: "Unfurnished",
  society: "Patancheru Industrial Zone",
  propertyType: "Industrial Land",
  area: { builtUp: "5 Acres" },
  price: "₹95 Cr",
  carpetArea: "N/A",
  pricePerSqft: "₹19,000 / sq.yd",
  location: { city: "Hyderabad", state: "Telangana", locality: "Patancheru", landmark: "NH-65 Highway" },
  carParking: "Open",
  description: "Prime industrial land parcel with highway connectivity.",
  images: imagesSet,
  amenities: ["Wide Road", "Electricity", "Water Supply"],
  mapLocation: { lat: 17.53, lng: 78.26 },
  intent: "high",
  postedOn: "this week",
  postedAt: "2025-09-17T16:00:00Z",
  contact: {
    name: "Praveen Iyer",
    phone: "+91 9811222277",
    email: "praveen.iyer@hydlands.com",
    whatsapp: "https://wa.me/919811222277",
    scheduleVisitLink: "https://calendly.com/praveen-land/visit"
  },
  highlights: ["Industrial hub", "Highway connectivity", "Prime location"],
  legalClearance: ["Industrial NOC", "Clear Title"]
},
{
  id: 70,
  title: "Mixed Use Building in Secunderabad, Hyderabad",
  status: "Ready to Move",
  transaction: "Resale",
  furnishing: "Semi-Furnished",
  society: "Secunderabad Plaza",
  propertyType: "Building",
  area: { builtUp: "20,000 sq.ft" },
  price: "₹65 Cr",
  carpetArea: "19,500 sq.ft",
  pricePerSqft: "₹32,500 / sq.ft",
  location: { city: "Hyderabad", state: "Telangana", locality: "Secunderabad", landmark: "Paradise Circle" },
  carParking: "Basement Parking",
  description: "Full commercial-residential mixed building with shops, offices & apartments.",
  images: imagesSet,
  amenities: ["Lift", "Security", "Power Backup"],
  mapLocation: { lat: 17.44, lng: 78.5 },
  intent: "high",
  postedOn: "today",
  postedAt: "2025-09-21T16:15:00Z",
  contact: {
    name: "Vikram Rao",
    phone: "+91 9811444499",
    email: "vikram.rao@hydplaza.com",
    whatsapp: "https://wa.me/919811444499",
    scheduleVisitLink: "https://calendly.com/vikram-building/visit"
  },
  highlights: ["Prime Secunderabad", "Mixed-use", "High rental yield"],
  legalClearance: ["RERA Approved", "Commercial NOC"]
},


// Noida Properties (71–80)

  {
    id: 71,
    title: "Premium 3 BHK in Noida Sector 76",
    status: "Ready to Move",
    transaction: "Resale",
    furnishing: "Semi-Furnished",
    society: "Skyline Residency",
    propertyType: "Apartment",
    bhk: "3 BHK",
    area: { builtUp: "1650 sq.ft" },
    price: "₹1.15 Cr",
    carpetArea: "1350 sq.ft",
    pricePerSqft: "₹6969 / sq.ft",
    location: { city: "Noida", state: "Uttar Pradesh", locality: "Sector 76", landmark: "Near Metro Station" },
    carParking: "1 Covered",
    description: "Spacious apartment with modular kitchen and ample sunlight.",
    images: imagesSet,
    amenities: ["Lift", "Gym", "Swimming Pool", "Club House"],
    floorPlan: "https://example.com/floorplan/3bhk-sector76.jpg",
    mapLocation: { lat: 28.597, lng: 77.379 },
    intent: "high",
    postedOn: "yesterday",
    postedAt: "2025-09-20T10:00:00Z",
    contact: {
      name: "Rajesh Kumar",
      phone: "+91 9876012345",
      email: "rajesh.kumar@noidahomes.com",
      whatsapp: "https://wa.me/919876012345",
    },
    highlights: ["Near Metro", "Well-ventilated", "Park Facing"],
    legalClearance: ["RERA Approved", "Clear Title"],
  },
  {
    id: 72,
    title: "Commercial Office in Sector 62 Noida",
    status: "Ready to Move",
    transaction: "New Property",
    furnishing: "Unfurnished",
    society: "Tech Tower",
    propertyType: "Office",
    area: { builtUp: "3200 sq.ft" },
    price: "₹2.8 Cr",
    carpetArea: "2800 sq.ft",
    pricePerSqft: "₹8750 / sq.ft",
    location: { city: "Noida", state: "Uttar Pradesh", locality: "Sector 62", landmark: "Near Fortis Hospital" },
    carParking: "2 Covered",
    description: "Grade-A office space suitable for IT/Corporate setup.",
    images: imagesSet,
    amenities: ["Power Backup", "Lift", "CCTV", "24x7 Security"],
    floorPlan: "https://example.com/floorplan/office-sector62.jpg",
    mapLocation: { lat: 28.628, lng: 77.365 },
    intent: "medium",
    postedOn: "this week",
    postedAt: "2025-09-18T14:00:00Z",
    contact: {
      name: "Pooja Sharma",
      phone: "+91 9876543321",
      email: "pooja.sharma@officespace.com",
      whatsapp: "https://wa.me/919876543321",
    },
    highlights: ["IT Hub", "High Rental Value", "Near Hospital"],
    legalClearance: ["Fire NOC", "RERA Approved"],
  },
  {
    id: 73,
    title: "Luxury Penthouse in Sector 150 Noida",
    status: "Ready to Move",
    transaction: "New Property",
    furnishing: "Furnished",
    society: "Lotus Greens",
    propertyType: "Penthouse",
    bhk: "4 BHK",
    area: { builtUp: "4200 sq.ft" },
    price: "₹3.75 Cr",
    carpetArea: "3800 sq.ft",
    pricePerSqft: "₹8928 / sq.ft",
    location: { city: "Noida", state: "Uttar Pradesh", locality: "Sector 150", landmark: "Near Yamuna Expressway" },
    carParking: "3 Covered",
    description: "Exclusive penthouse with rooftop deck and private pool.",
    images: imagesSet,
    amenities: ["Private Pool", "Rooftop Lounge", "Gym", "Spa"],
    floorPlan: "https://example.com/floorplan/penthouse-150.jpg",
    mapLocation: { lat: 28.506, lng: 77.476 },
    intent: "high",
    postedOn: "today",
    postedAt: "2025-09-21T09:00:00Z",
    contact: {
      name: "Anita Mehra",
      phone: "+91 9811122334",
      email: "anita.mehra@luxurypenthouses.com",
      whatsapp: "https://wa.me/919811122334",
    },
    highlights: ["Exclusive living", "Private deck", "Green surroundings"],
    legalClearance: ["RERA Approved", "Loan Available"],
  },
  {
    id: 74,
    title: "Warehouse for Rent in Sector 63 Noida",
    status: "Ready to Move",
    transaction: "New Property",
    furnishing: "Unfurnished",
    society: "Industrial Estate",
    propertyType: "Warehouse",
    area: { builtUp: "15000 sq.ft" },
    price: "₹4.5 Lac/month",
    carpetArea: "14000 sq.ft",
    pricePerSqft: "₹30 / sq.ft",
    location: { city: "Noida", state: "Uttar Pradesh", locality: "Sector 63", landmark: "Near Electronic City" },
    carParking: "Truck Parking Available",
    description: "Large warehouse with docking bays and power backup.",
    images: imagesSet,
    amenities: ["Docking Bay", "Power Backup", "Wide Roads", "Security"],
    mapLocation: { lat: 28.630, lng: 77.375 },
    intent: "medium",
    postedOn: "this week",
    postedAt: "2025-09-17T12:30:00Z",
    contact: {
      name: "Manoj Gupta",
      phone: "+91 9876654321",
      email: "manoj.gupta@warehousedeals.com",
      whatsapp: "https://wa.me/919876654321",
    },
    highlights: ["NH-24 Access", "Industrial Zone", "High Storage Capacity"],
    legalClearance: ["Factory License", "RERA"],
  },
  {
    id: 75,
    title: "Hotel Apartment in Sector 135 Noida Expressway",
    status: "Ready to Move",
    transaction: "New Property",
    furnishing: "Furnished",
    society: "Business Suites",
    propertyType: "Hotel Apartment",
    bhk: "Studio",
    area: { builtUp: "650 sq.ft" },
    price: "₹75 Lac",
    carpetArea: "550 sq.ft",
    pricePerSqft: "₹11,538 / sq.ft",
    location: { city: "Noida", state: "Uttar Pradesh", locality: "Sector 135", landmark: "Near Infosys Campus" },
    carParking: "1 Covered",
    description: "Fully serviced apartment with hotel facilities and rental yield.",
    images: imagesSet,
    amenities: ["Housekeeping", "Swimming Pool", "Gym", "Concierge"],
    floorPlan: "https://example.com/floorplan/hotelapartment-135.jpg",
    mapLocation: { lat: 28.492, lng: 77.416 },
    intent: "medium",
    postedOn: "yesterday",
    postedAt: "2025-09-20T11:00:00Z",
    contact: {
      name: "Sneha Kapoor",
      phone: "+91 9822012345",
      email: "sneha.kapoor@investnoida.com",
      whatsapp: "https://wa.me/919822012345",
    },
    highlights: ["Rental Income", "Near Corporate Offices", "Serviced Facilities"],
    legalClearance: ["RERA Approved", "Bank Tie-ups"],
  },
  {
    id: 76,
    title: "Mixed Use Land in Sector 143 Noida",
    status: "Under Construction",
    transaction: "New Property",
    furnishing: "Unfurnished",
    society: "Expressway Hub",
    propertyType: "Mixed Use Land",
    area: { builtUp: "2 Acres" },
    price: "₹28 Cr",
    carpetArea: "N/A",
    pricePerSqft: "₹12,800 / sq.yd",
    location: { city: "Noida", state: "Uttar Pradesh", locality: "Sector 143", landmark: "Near Metro Station" },
    carParking: "Open",
    description: "Land parcel suitable for commercial + residential projects.",
    images: imagesSet,
    amenities: ["Road Connectivity", "Electricity", "Water Supply"],
    mapLocation: { lat: 28.529, lng: 77.411 },
    intent: "high",
    postedOn: "this week",
    postedAt: "2025-09-18T10:45:00Z",
    contact: {
      name: "Arun Yadav",
      phone: "+91 9877009876",
      email: "arun.yadav@landdeals.com",
      whatsapp: "https://wa.me/919877009876",
    },
    highlights: ["Expressway Access", "Metro Nearby", "Ideal Investment"],
    legalClearance: ["RERA", "Clear Title", "NA Order"],
  },
  {
    id: 77,
    title: "Showroom Space in Sector 18 Noida",
    status: "Ready to Move",
    transaction: "Resale",
    furnishing: "Semi-Furnished",
    society: "Central Plaza",
    propertyType: "Showroom",
    area: { builtUp: "3000 sq.ft" },
    price: "₹5.25 Cr",
    carpetArea: "2600 sq.ft",
    pricePerSqft: "₹17,500 / sq.ft",
    location: { city: "Noida", state: "Uttar Pradesh", locality: "Sector 18", landmark: "Near GIP Mall" },
    carParking: "2 Open",
    description: "Prime showroom suitable for retail or restaurant.",
    images: imagesSet,
    amenities: ["Power Backup", "Security", "Ample Parking"],
    mapLocation: { lat: 28.570, lng: 77.326 },
    intent: "high",
    postedOn: "yesterday",
    postedAt: "2025-09-20T14:30:00Z",
    contact: {
      name: "Deepak Malhotra",
      phone: "+91 9810098765",
      email: "deepak.m@retailnoida.com",
      whatsapp: "https://wa.me/919810098765",
    },
    highlights: ["High Footfall", "Near GIP Mall", "Retail Hub"],
    legalClearance: ["RERA", "Shop License"],
  },
  {
    id: 78,
    title: "Factory Space in Sector 80 Noida",
    status: "Ready to Move",
    transaction: "Resale",
    furnishing: "Unfurnished",
    society: "Industrial Area",
    propertyType: "Factory",
    area: { builtUp: "10000 sq.ft" },
    price: "₹6 Cr",
    carpetArea: "9500 sq.ft",
    pricePerSqft: "₹6000 / sq.ft",
    location: { city: "Noida", state: "Uttar Pradesh", locality: "Sector 80", landmark: "Near Dadri Road" },
    carParking: "Truck Parking Available",
    description: "Factory unit with heavy power connection and wide roads.",
    images: imagesSet,
    amenities: ["Power Supply", "Water Connection", "CCTV"],
    mapLocation: { lat: 28.578, lng: 77.373 },
    intent: "medium",
    postedOn: "this week",
    postedAt: "2025-09-19T15:00:00Z",
    contact: {
      name: "Vipul Jain",
      phone: "+91 9876004321",
      email: "vipul.jain@factorydeal.com",
      whatsapp: "https://wa.me/919876004321",
    },
    highlights: ["Industrial Approved", "Wide Roads", "Clear Papers"],
    legalClearance: ["Factory License", "RERA"],
  },
  {
    id: 79,
    title: "Residential Plot in Sector 150 Noida",
    status: "Ready to Move",
    transaction: "New Property",
    furnishing: "Unfurnished",
    society: "Green Enclave",
    propertyType: "Land",
    area: { builtUp: "200 sq.yd" },
    price: "₹1.5 Cr",
    carpetArea: "N/A",
    pricePerSqft: "₹75,000 / sq.yd",
    location: { city: "Noida", state: "Uttar Pradesh", locality: "Sector 150", landmark: "Near Sports City" },
    carParking: "N/A",
    description: "Residential plot ideal for villa or duplex construction.",
    images: imagesSet,
    amenities: ["Gated Community", "Parks", "Electricity"],
    mapLocation: { lat: 28.508, lng: 77.487 },
    intent: "high",
    postedOn: "today",
    postedAt: "2025-09-21T08:45:00Z",
    contact: {
      name: "Aakash Singh",
      phone: "+91 9822015678",
      email: "aakash.singh@plotsale.com",
      whatsapp: "https://wa.me/919822015678",
    },
    highlights: ["Sports City Access", "Wide Roads", "Premium Location"],
    legalClearance: ["RERA", "NA Order"],
  },
  {
    id: 80,
    title: "Builder Floor in Sector 52 Noida",
    status: "Under Construction",
    transaction: "New Property",
    furnishing: "Semi-Furnished",
    society: "Elite Floors",
    propertyType: "Floor",
    bhk: "3 BHK",
    area: { builtUp: "1800 sq.ft" },
    price: "₹1.05 Cr",
    carpetArea: "1500 sq.ft",
    pricePerSqft: "₹5833 / sq.ft",
    location: { city: "Noida", state: "Uttar Pradesh", locality: "Sector 52", landmark: "Near Metro" },
    carParking: "1 Covered",
    description: "Independent floor with modern interiors and wide balcony.",
    images: imagesSet,
    amenities: ["Lift", "Parking", "Power Backup"],
    floorPlan: "https://example.com/floorplan/floor-52.jpg",
    mapLocation: { lat: 28.578, lng: 77.350 },
    intent: "medium",
    postedOn: "this week",
    postedAt: "2025-09-18T16:20:00Z",
    contact: {
      name: "Harsh Vardhan",
      phone: "+91 9877001122",
      email: "harsh.vardhan@floordeals.com",
      whatsapp: "https://wa.me/919877001122",
    },
    highlights: ["Independent Floor", "Close to Metro", "Modern Interiors"],
    legalClearance: ["RERA Approved", "Bank Loan Available"],
  }





 
];

export default dummyProperties;
